/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_DFullTime_H_
#define	_DSRC_DFullTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DYear.h"
#include "DSRC_DMonth.h"
#include "DSRC_DDay.h"
#include "DSRC_DHour.h"
#include "DSRC_DMinute.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_DFullTime */
typedef struct DSRC_DFullTime {
	DSRC_DYear_t	 year;
	DSRC_DMonth_t	 month;
	DSRC_DDay_t	 day;
	DSRC_DHour_t	 hour;
	DSRC_DMinute_t	 minute;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_DFullTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_DFullTime;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_DFullTime_H_ */
#include <asn_internal.h>
