/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_SpeedConfidence_H_
#define	_DSRC_SpeedConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_SpeedConfidence {
	DSRC_SpeedConfidence_unavailable	= 0,
	DSRC_SpeedConfidence_prec100ms	= 1,
	DSRC_SpeedConfidence_prec10ms	= 2,
	DSRC_SpeedConfidence_prec5ms	= 3,
	DSRC_SpeedConfidence_prec1ms	= 4,
	DSRC_SpeedConfidence_prec0_1ms	= 5,
	DSRC_SpeedConfidence_prec0_05ms	= 6,
	DSRC_SpeedConfidence_prec0_01ms	= 7
} e_DSRC_SpeedConfidence;

/* DSRC_SpeedConfidence */
typedef long	 DSRC_SpeedConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_SpeedConfidence;
asn_struct_free_f DSRC_SpeedConfidence_free;
asn_struct_print_f DSRC_SpeedConfidence_print;
asn_constr_check_f DSRC_SpeedConfidence_constraint;
ber_type_decoder_f DSRC_SpeedConfidence_decode_ber;
der_type_encoder_f DSRC_SpeedConfidence_encode_der;
xer_type_decoder_f DSRC_SpeedConfidence_decode_xer;
xer_type_encoder_f DSRC_SpeedConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_SpeedConfidence_H_ */
#include <asn_internal.h>
