/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#include "DSRC_BasicSafetyMessage.h"

static asn_TYPE_member_t asn_MBR_DSRC_BasicSafetyMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DSRC_BasicSafetyMessage, msgID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_DSRCmsgID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msgID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DSRC_BasicSafetyMessage, blob1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_BSMblob,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"blob1"
		},
	{ ATF_POINTER, 4, offsetof(struct DSRC_BasicSafetyMessage, safetyExt),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_VehicleSafetyExtension,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"safetyExt"
		},
	{ ATF_POINTER, 3, offsetof(struct DSRC_BasicSafetyMessage, status),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_VehicleStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"status"
		},
	{ ATF_POINTER, 2, offsetof(struct DSRC_BasicSafetyMessage, vehicleDataV2VI),
		(ASN_TAG_CLASS_CONTEXT | (128 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_VehicleDataV2VI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleDataV2VI"
		},
	{ ATF_POINTER, 1, offsetof(struct DSRC_BasicSafetyMessage, testDataFrameV2VI),
		(ASN_TAG_CLASS_CONTEXT | (129 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_TestDataFrameV2VI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"testDataFrameV2VI"
		},
};
static const ber_tlv_tag_t asn_DEF_DSRC_BasicSafetyMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DSRC_BasicSafetyMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* blob1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* safetyExt */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* status */
    { (ASN_TAG_CLASS_CONTEXT | (128 << 2)), 4, 0, 0 }, /* vehicleDataV2VI */
    { (ASN_TAG_CLASS_CONTEXT | (129 << 2)), 5, 0, 0 } /* testDataFrameV2VI */
};
static asn_SEQUENCE_specifics_t asn_SPC_DSRC_BasicSafetyMessage_specs_1 = {
	sizeof(struct DSRC_BasicSafetyMessage),
	offsetof(struct DSRC_BasicSafetyMessage, _asn_ctx),
	asn_MAP_DSRC_BasicSafetyMessage_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DSRC_BasicSafetyMessage = {
	"DSRC_BasicSafetyMessage",
	"DSRC_BasicSafetyMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No UPER support, use "-gen-PER" to enable */
	0, 0,	/* No APER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DSRC_BasicSafetyMessage_tags_1,
	sizeof(asn_DEF_DSRC_BasicSafetyMessage_tags_1)
		/sizeof(asn_DEF_DSRC_BasicSafetyMessage_tags_1[0]), /* 1 */
	asn_DEF_DSRC_BasicSafetyMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_DSRC_BasicSafetyMessage_tags_1)
		/sizeof(asn_DEF_DSRC_BasicSafetyMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DSRC_BasicSafetyMessage_1,
	6,	/* Elements count */
	&asn_SPC_DSRC_BasicSafetyMessage_specs_1	/* Additional specs */
};

