/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_RainSensor_H_
#define	_DSRC_RainSensor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_RainSensor {
	DSRC_RainSensor_none	= 0,
	DSRC_RainSensor_lightMist	= 1,
	DSRC_RainSensor_heavyMist	= 2,
	DSRC_RainSensor_lightRainOrDrizzle	= 3,
	DSRC_RainSensor_rain	= 4,
	DSRC_RainSensor_moderateRain	= 5,
	DSRC_RainSensor_heavyRain	= 6,
	DSRC_RainSensor_heavyDownpour	= 7
} e_DSRC_RainSensor;

/* DSRC_RainSensor */
typedef long	 DSRC_RainSensor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_RainSensor;
asn_struct_free_f DSRC_RainSensor_free;
asn_struct_print_f DSRC_RainSensor_print;
asn_constr_check_f DSRC_RainSensor_constraint;
ber_type_decoder_f DSRC_RainSensor_decode_ber;
der_type_encoder_f DSRC_RainSensor_encode_der;
xer_type_decoder_f DSRC_RainSensor_decode_xer;
xer_type_encoder_f DSRC_RainSensor_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_RainSensor_H_ */
#include <asn_internal.h>
