/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_CommonSafetyRequest_H_
#define	_DSRC_CommonSafetyRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_TemporaryID.h"
#include "DSRC_RequestedItem.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_CommonSafetyRequest */
typedef struct DSRC_CommonSafetyRequest {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	*msgCnt	/* OPTIONAL */;
	DSRC_TemporaryID_t	*id	/* OPTIONAL */;
	struct DSRC_CommonSafetyRequest__requests {
		A_SEQUENCE_OF(DSRC_RequestedItem_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} requests;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_CommonSafetyRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_CommonSafetyRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_CommonSafetyRequest_H_ */
#include <asn_internal.h>
