/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_GPSstatus_H_
#define	_DSRC_GPSstatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_GPSstatus {
	DSRC_GPSstatus_unavailable	= 0,
	DSRC_GPSstatus_isHealthy	= 1,
	DSRC_GPSstatus_isMonitored	= 2,
	DSRC_GPSstatus_baseStationType	= 3,
	DSRC_GPSstatus_aPDOPofUnder5	= 4,
	DSRC_GPSstatus_inViewOfUnder5	= 5,
	DSRC_GPSstatus_localCorrectionsPresent	= 6,
	DSRC_GPSstatus_networkCorrectionsPresent	= 7
} e_DSRC_GPSstatus;

/* DSRC_GPSstatus */
typedef BIT_STRING_t	 DSRC_GPSstatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_GPSstatus;
asn_struct_free_f DSRC_GPSstatus_free;
asn_struct_print_f DSRC_GPSstatus_print;
asn_constr_check_f DSRC_GPSstatus_constraint;
ber_type_decoder_f DSRC_GPSstatus_decode_ber;
der_type_encoder_f DSRC_GPSstatus_encode_der;
xer_type_decoder_f DSRC_GPSstatus_decode_xer;
xer_type_encoder_f DSRC_GPSstatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_GPSstatus_H_ */
#include <asn_internal.h>
