/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_BasicSafetyMessage_H_
#define	_DSRC_BasicSafetyMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_BSMblob.h"
#include "DSRC_VehicleSafetyExtension.h"
#include "DSRC_VehicleStatus.h"
#include "DSRC_VehicleDataV2VI.h"
#include "DSRC_TestDataFrameV2VI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_BasicSafetyMessage */
typedef struct DSRC_BasicSafetyMessage {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_BSMblob_t	 blob1;
	DSRC_VehicleSafetyExtension_t	*safetyExt	/* OPTIONAL */;
	DSRC_VehicleStatus_t	*status	/* OPTIONAL */;
	DSRC_VehicleDataV2VI_t	*vehicleDataV2VI	/* OPTIONAL */;
	DSRC_TestDataFrameV2VI_t	*testDataFrameV2VI	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_BasicSafetyMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_BasicSafetyMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_BasicSafetyMessage_H_ */
#include <asn_internal.h>
