/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_DirectionOfUse_H_
#define	_DSRC_DirectionOfUse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_DirectionOfUse {
	DSRC_DirectionOfUse_forward	= 0,
	DSRC_DirectionOfUse_reverse	= 1,
	DSRC_DirectionOfUse_both	= 2
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_DirectionOfUse;

/* DSRC_DirectionOfUse */
typedef long	 DSRC_DirectionOfUse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_DirectionOfUse;
asn_struct_free_f DSRC_DirectionOfUse_free;
asn_struct_print_f DSRC_DirectionOfUse_print;
asn_constr_check_f DSRC_DirectionOfUse_constraint;
ber_type_decoder_f DSRC_DirectionOfUse_decode_ber;
der_type_encoder_f DSRC_DirectionOfUse_encode_der;
xer_type_decoder_f DSRC_DirectionOfUse_decode_xer;
xer_type_encoder_f DSRC_DirectionOfUse_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_DirectionOfUse_H_ */
#include <asn_internal.h>
