/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_BrakeAppliedPressure_H_
#define	_DSRC_BrakeAppliedPressure_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_BrakeAppliedPressure {
	DSRC_BrakeAppliedPressure_unavailable	= 0,
	DSRC_BrakeAppliedPressure_minPressure	= 1,
	DSRC_BrakeAppliedPressure_bkLvl_2	= 2,
	DSRC_BrakeAppliedPressure_bkLvl_3	= 3,
	DSRC_BrakeAppliedPressure_bkLvl_4	= 4,
	DSRC_BrakeAppliedPressure_bkLvl_5	= 5,
	DSRC_BrakeAppliedPressure_bkLvl_6	= 6,
	DSRC_BrakeAppliedPressure_bkLvl_7	= 7,
	DSRC_BrakeAppliedPressure_bkLvl_8	= 8,
	DSRC_BrakeAppliedPressure_bkLvl_9	= 9,
	DSRC_BrakeAppliedPressure_bkLvl_10	= 10,
	DSRC_BrakeAppliedPressure_bkLvl_11	= 11,
	DSRC_BrakeAppliedPressure_bkLvl_12	= 12,
	DSRC_BrakeAppliedPressure_bkLvl_13	= 13,
	DSRC_BrakeAppliedPressure_bkLvl_14	= 14,
	DSRC_BrakeAppliedPressure_maxPressure	= 15
} e_DSRC_BrakeAppliedPressure;

/* DSRC_BrakeAppliedPressure */
typedef long	 DSRC_BrakeAppliedPressure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_BrakeAppliedPressure;
asn_struct_free_f DSRC_BrakeAppliedPressure_free;
asn_struct_print_f DSRC_BrakeAppliedPressure_print;
asn_constr_check_f DSRC_BrakeAppliedPressure_constraint;
ber_type_decoder_f DSRC_BrakeAppliedPressure_decode_ber;
der_type_encoder_f DSRC_BrakeAppliedPressure_encode_der;
xer_type_decoder_f DSRC_BrakeAppliedPressure_decode_xer;
xer_type_encoder_f DSRC_BrakeAppliedPressure_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_BrakeAppliedPressure_H_ */
#include <asn_internal.h>
