/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_WiperStatusRear_H_
#define	_DSRC_WiperStatusRear_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_WiperStatusRear {
	DSRC_WiperStatusRear_unavailable	= 0,
	DSRC_WiperStatusRear_off	= 1,
	DSRC_WiperStatusRear_intermittent	= 2,
	DSRC_WiperStatusRear_low	= 3,
	DSRC_WiperStatusRear_high	= 4,
	DSRC_WiperStatusRear_washerInUse	= 126,
	DSRC_WiperStatusRear_automaticPresent	= 127
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_WiperStatusRear;

/* DSRC_WiperStatusRear */
typedef long	 DSRC_WiperStatusRear_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_WiperStatusRear;
asn_struct_free_f DSRC_WiperStatusRear_free;
asn_struct_print_f DSRC_WiperStatusRear_print;
asn_constr_check_f DSRC_WiperStatusRear_constraint;
ber_type_decoder_f DSRC_WiperStatusRear_decode_ber;
der_type_encoder_f DSRC_WiperStatusRear_encode_der;
xer_type_decoder_f DSRC_WiperStatusRear_decode_xer;
xer_type_encoder_f DSRC_WiperStatusRear_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_WiperStatusRear_H_ */
#include <asn_internal.h>
