/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_Extent_H_
#define	_DSRC_Extent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_Extent {
	DSRC_Extent_useInstantlyOnly	= 0,
	DSRC_Extent_useFor3meters	= 1,
	DSRC_Extent_useFor10meters	= 2,
	DSRC_Extent_useFor50meters	= 3,
	DSRC_Extent_useFor100meters	= 4,
	DSRC_Extent_useFor500meters	= 5,
	DSRC_Extent_useFor1000meters	= 6,
	DSRC_Extent_useFor5000meters	= 7,
	DSRC_Extent_useFor10000meters	= 8,
	DSRC_Extent_useFor50000meters	= 9,
	DSRC_Extent_useFor100000meters	= 10,
	DSRC_Extent_forever	= 127
} e_DSRC_Extent;

/* DSRC_Extent */
typedef long	 DSRC_Extent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_Extent;
asn_struct_free_f DSRC_Extent_free;
asn_struct_print_f DSRC_Extent_print;
asn_constr_check_f DSRC_Extent_constraint;
ber_type_decoder_f DSRC_Extent_decode_ber;
der_type_encoder_f DSRC_Extent_encode_der;
xer_type_decoder_f DSRC_Extent_decode_xer;
xer_type_encoder_f DSRC_Extent_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_Extent_H_ */
#include <asn_internal.h>
