/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_SPAT_H_
#define	_DSRC_SPAT_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_DescriptiveName.h"
#include "DSRC_IntersectionState.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_SPAT */
typedef struct DSRC_SPAT {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_DescriptiveName_t	*name	/* OPTIONAL */;
	struct DSRC_SPAT__intersections {
		A_SEQUENCE_OF(DSRC_IntersectionState_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} intersections;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_SPAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_SPAT;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_SPAT_H_ */
#include <asn_internal.h>
