/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_J1939data_H_
#define	_DSRC_J1939data_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_TrailerWeight.h"
#include "DSRC_CargoWeight.h"
#include "DSRC_SteeringAxleTemperature.h"
#include "DSRC_DriveAxleLocation.h"
#include "DSRC_DriveAxleLiftAirPressure.h"
#include "DSRC_DriveAxleTemperature.h"
#include "DSRC_DriveAxleLubePressure.h"
#include "DSRC_SteeringAxleLubePressure.h"
#include <asn_SEQUENCE_OF.h>
#include "DSRC_TireLocation.h"
#include "DSRC_TirePressure.h"
#include "DSRC_TireTemp.h"
#include "DSRC_WheelSensorStatus.h"
#include "DSRC_WheelEndElectFault.h"
#include "DSRC_TireLeakageRate.h"
#include "DSRC_TirePressureThresholdDetection.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>
#include "DSRC_AxleLocation.h"
#include "DSRC_AxleWeight.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_J1939data */
typedef struct DSRC_J1939data {
	struct DSRC_J1939data__tires {
		A_SEQUENCE_OF(struct DSRC_J1939data__tires__Member {
			DSRC_TireLocation_t	*location	/* OPTIONAL */;
			DSRC_TirePressure_t	*pressure	/* OPTIONAL */;
			DSRC_TireTemp_t	*temp	/* OPTIONAL */;
			DSRC_WheelSensorStatus_t	*wheelSensorStatus	/* OPTIONAL */;
			DSRC_WheelEndElectFault_t	*wheelEndElectFault	/* OPTIONAL */;
			DSRC_TireLeakageRate_t	*leakageRate	/* OPTIONAL */;
			DSRC_TirePressureThresholdDetection_t	*detection	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tires;
	struct DSRC_J1939data__axle {
		A_SEQUENCE_OF(struct DSRC_J1939data__axle__Member {
			DSRC_AxleLocation_t	*location	/* OPTIONAL */;
			DSRC_AxleWeight_t	*weight	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *axle;
	DSRC_TrailerWeight_t	*trailerWeight	/* OPTIONAL */;
	DSRC_CargoWeight_t	*cargoWeight	/* OPTIONAL */;
	DSRC_SteeringAxleTemperature_t	*steeringAxleTemperature	/* OPTIONAL */;
	DSRC_DriveAxleLocation_t	*driveAxleLocation	/* OPTIONAL */;
	DSRC_DriveAxleLiftAirPressure_t	*driveAxleLiftAirPressure	/* OPTIONAL */;
	DSRC_DriveAxleTemperature_t	*driveAxleTemperature	/* OPTIONAL */;
	DSRC_DriveAxleLubePressure_t	*driveAxleLubePressure	/* OPTIONAL */;
	DSRC_SteeringAxleLubePressure_t	*steeringAxleLubePressure	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_J1939data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_J1939data;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_J1939data_H_ */
#include <asn_internal.h>
