/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_DSRCmsgID_H_
#define	_DSRC_DSRCmsgID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_DSRCmsgID {
	DSRC_DSRCmsgID_reserved	= 0,
	DSRC_DSRCmsgID_alaCarteMessage	= 1,
	DSRC_DSRCmsgID_basicSafetyMessage	= 2,
	DSRC_DSRCmsgID_basicSafetyMessageVerbose	= 3,
	DSRC_DSRCmsgID_commonSafetyRequest	= 4,
	DSRC_DSRCmsgID_emergencyVehicleAlert	= 5,
	DSRC_DSRCmsgID_intersectionCollisionAlert	= 6,
	DSRC_DSRCmsgID_mapData	= 7,
	DSRC_DSRCmsgID_nmeaCorrections	= 8,
	DSRC_DSRCmsgID_probeDataManagement	= 9,
	DSRC_DSRCmsgID_probeVehicleData	= 10,
	DSRC_DSRCmsgID_roadSideAlert	= 11,
	DSRC_DSRCmsgID_rtcmCorrections	= 12,
	DSRC_DSRCmsgID_signalPhaseAndTimingMessage	= 13,
	DSRC_DSRCmsgID_signalRequestMessage	= 14,
	DSRC_DSRCmsgID_signalStatusMessage	= 15,
	DSRC_DSRCmsgID_travelerInformation	= 16
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_DSRCmsgID;

/* DSRC_DSRCmsgID */
typedef long	 DSRC_DSRCmsgID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_DSRCmsgID;
asn_struct_free_f DSRC_DSRCmsgID_free;
asn_struct_print_f DSRC_DSRCmsgID_print;
asn_constr_check_f DSRC_DSRCmsgID_constraint;
ber_type_decoder_f DSRC_DSRCmsgID_decode_ber;
der_type_encoder_f DSRC_DSRCmsgID_encode_der;
xer_type_decoder_f DSRC_DSRCmsgID_decode_xer;
xer_type_encoder_f DSRC_DSRCmsgID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_DSRCmsgID_H_ */
#include <asn_internal.h>
