/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_VehicleSize_H_
#define	_DSRC_VehicleSize_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_VehicleWidth.h"
#include "DSRC_VehicleLength.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_VehicleSize */
typedef struct DSRC_VehicleSize {
	DSRC_VehicleWidth_t	 width;
	DSRC_VehicleLength_t	 length;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_VehicleSize_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_VehicleSize;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_VehicleSize_H_ */
#include <asn_internal.h>
