/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_RTCM_Corrections_H_
#define	_DSRC_RTCM_Corrections_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_RTCM-Revision.h"
#include "DSRC_FullPositionVector.h"
#include "DSRC_RTCMHeader.h"
#include "DSRC_RTCMmsg.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_RTCM-Corrections */
typedef struct DSRC_RTCM_Corrections {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	 msgCnt;
	DSRC_RTCM_Revision_t	 rev;
	DSRC_FullPositionVector_t	*anchorPoint	/* OPTIONAL */;
	DSRC_RTCMHeader_t	 rtcmHeader;
	struct DSRC_RTCM_Corrections__rtcmSets {
		A_SEQUENCE_OF(DSRC_RTCMmsg_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rtcmSets;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_RTCM_Corrections_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_RTCM_Corrections;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_RTCM_Corrections_H_ */
#include <asn_internal.h>
