/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_ConfidenceSet_H_
#define	_DSRC_ConfidenceSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_AccelSteerYawRateConfidence.h"
#include "DSRC_SpeedandHeadingandThrottleConfidence.h"
#include "DSRC_TimeConfidence.h"
#include "DSRC_PositionConfidenceSet.h"
#include "DSRC_SteeringWheelAngleConfidence.h"
#include "DSRC_ThrottleConfidence.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_ConfidenceSet */
typedef struct DSRC_ConfidenceSet {
	DSRC_AccelSteerYawRateConfidence_t	*accelConfidence	/* OPTIONAL */;
	DSRC_SpeedandHeadingandThrottleConfidence_t	*speedConfidence	/* OPTIONAL */;
	DSRC_TimeConfidence_t	*timeConfidence	/* OPTIONAL */;
	DSRC_PositionConfidenceSet_t	*posConfidence	/* OPTIONAL */;
	DSRC_SteeringWheelAngleConfidence_t	*steerConfidence	/* OPTIONAL */;
	DSRC_ThrottleConfidence_t	*throttleConfidence	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_ConfidenceSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_ConfidenceSet;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_ConfidenceSet_H_ */
#include <asn_internal.h>
