/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_ValidRegion_H_
#define	_DSRC_ValidRegion_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_HeadingSlice.h"
#include "DSRC_Extent.h"
#include "DSRC_ShapePointSet.h"
#include "DSRC_Circle.h"
#include "DSRC_RegionPointSet.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_ValidRegion__area_PR {
	DSRC_ValidRegion__area_PR_NOTHING,	/* No components present */
	DSRC_ValidRegion__area_PR_shapePointSet,
	DSRC_ValidRegion__area_PR_circle,
	DSRC_ValidRegion__area_PR_regionPointSet
} DSRC_ValidRegion__area_PR;

/* DSRC_ValidRegion */
typedef struct DSRC_ValidRegion {
	DSRC_HeadingSlice_t	 direction;
	DSRC_Extent_t	*extent	/* OPTIONAL */;
	struct DSRC_ValidRegion__area {
		DSRC_ValidRegion__area_PR present;
		union DSRC_ValidRegion__area_u {
			DSRC_ShapePointSet_t	 shapePointSet;
			DSRC_Circle_t	 circle;
			DSRC_RegionPointSet_t	 regionPointSet;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} area;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_ValidRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_ValidRegion;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_ValidRegion_H_ */
#include <asn_internal.h>
