/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_VehicleIdent_H_
#define	_DSRC_VehicleIdent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DescriptiveName.h"
#include "DSRC_VINstring.h"
#include <IA5String.h>
#include "DSRC_TemporaryID.h"
#include "DSRC_VehicleType.h"
#include "DSRC_VehicleGroupAffected.h"
#include "DSRC_ResponderGroupAffected.h"
#include "DSRC_IncidentResponseEquipment.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_VehicleIdent__vehicleClass_PR {
	DSRC_VehicleIdent__vehicleClass_PR_NOTHING,	/* No components present */
	DSRC_VehicleIdent__vehicleClass_PR_vGroup,
	DSRC_VehicleIdent__vehicleClass_PR_rGroup,
	DSRC_VehicleIdent__vehicleClass_PR_rEquip
} DSRC_VehicleIdent__vehicleClass_PR;

/* DSRC_VehicleIdent */
typedef struct DSRC_VehicleIdent {
	DSRC_DescriptiveName_t	*name	/* OPTIONAL */;
	DSRC_VINstring_t	*vin	/* OPTIONAL */;
	IA5String_t	*ownerCode	/* OPTIONAL */;
	DSRC_TemporaryID_t	*id	/* OPTIONAL */;
	DSRC_VehicleType_t	*vehicleType	/* OPTIONAL */;
	struct DSRC_VehicleIdent__vehicleClass {
		DSRC_VehicleIdent__vehicleClass_PR present;
		union DSRC_VehicleIdent__vehicleClass_u {
			DSRC_VehicleGroupAffected_t	 vGroup;
			DSRC_ResponderGroupAffected_t	 rGroup;
			DSRC_IncidentResponseEquipment_t	 rEquip;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vehicleClass;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_VehicleIdent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_VehicleIdent;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_VehicleIdent_H_ */
#include <asn_internal.h>
