/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_VerticalAccelerationThreshold_H_
#define	_DSRC_VerticalAccelerationThreshold_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_VerticalAccelerationThreshold {
	DSRC_VerticalAccelerationThreshold_allOff	= 0,
	DSRC_VerticalAccelerationThreshold_leftFront	= 1,
	DSRC_VerticalAccelerationThreshold_leftRear	= 2,
	DSRC_VerticalAccelerationThreshold_rightFront	= 4,
	DSRC_VerticalAccelerationThreshold_rightRear	= 8
} e_DSRC_VerticalAccelerationThreshold;

/* DSRC_VerticalAccelerationThreshold */
typedef BIT_STRING_t	 DSRC_VerticalAccelerationThreshold_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_VerticalAccelerationThreshold;
asn_struct_free_f DSRC_VerticalAccelerationThreshold_free;
asn_struct_print_f DSRC_VerticalAccelerationThreshold_print;
asn_constr_check_f DSRC_VerticalAccelerationThreshold_constraint;
ber_type_decoder_f DSRC_VerticalAccelerationThreshold_decode_ber;
der_type_encoder_f DSRC_VerticalAccelerationThreshold_encode_der;
xer_type_decoder_f DSRC_VerticalAccelerationThreshold_decode_xer;
xer_type_encoder_f DSRC_VerticalAccelerationThreshold_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_VerticalAccelerationThreshold_H_ */
#include <asn_internal.h>
