/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#include "DSRC_VehicleStatusDeviceTypeTag.h"

int
DSRC_VehicleStatusDeviceTypeTag_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
DSRC_VehicleStatusDeviceTypeTag_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
DSRC_VehicleStatusDeviceTypeTag_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	DSRC_VehicleStatusDeviceTypeTag_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
DSRC_VehicleStatusDeviceTypeTag_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	DSRC_VehicleStatusDeviceTypeTag_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
DSRC_VehicleStatusDeviceTypeTag_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	DSRC_VehicleStatusDeviceTypeTag_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
DSRC_VehicleStatusDeviceTypeTag_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	DSRC_VehicleStatusDeviceTypeTag_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
DSRC_VehicleStatusDeviceTypeTag_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	DSRC_VehicleStatusDeviceTypeTag_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
DSRC_VehicleStatusDeviceTypeTag_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	DSRC_VehicleStatusDeviceTypeTag_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const asn_INTEGER_enum_map_t asn_MAP_DSRC_VehicleStatusDeviceTypeTag_value2enum_1[] = {
	{ 0,	7,	"unknown" },
	{ 1,	6,	"lights" },
	{ 2,	6,	"wipers" },
	{ 3,	6,	"brakes" },
	{ 4,	4,	"stab" },
	{ 5,	4,	"trac" },
	{ 6,	3,	"abs" },
	{ 7,	4,	"sunS" },
	{ 8,	5,	"rainS" },
	{ 9,	7,	"airTemp" },
	{ 10,	8,	"steering" },
	{ 11,	14,	"vertAccelThres" },
	{ 12,	9,	"vertAccel" },
	{ 13,	12,	"hozAccelLong" },
	{ 14,	11,	"hozAccelLat" },
	{ 15,	11,	"hozAccelCon" },
	{ 16,	9,	"accel4way" },
	{ 17,	13,	"confidenceSet" },
	{ 18,	6,	"obDist" },
	{ 19,	8,	"obDirect" },
	{ 20,	3,	"yaw" },
	{ 21,	10,	"yawRateCon" },
	{ 22,	8,	"dateTime" },
	{ 23,	7,	"fullPos" },
	{ 24,	10,	"position2D" },
	{ 25,	10,	"position3D" },
	{ 26,	7,	"vehicle" },
	{ 27,	10,	"speedHeadC" },
	{ 28,	6,	"speedC" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_DSRC_VehicleStatusDeviceTypeTag_enum2value_1[] = {
	6,	/* abs(6) */
	16,	/* accel4way(16) */
	9,	/* airTemp(9) */
	3,	/* brakes(3) */
	17,	/* confidenceSet(17) */
	22,	/* dateTime(22) */
	23,	/* fullPos(23) */
	15,	/* hozAccelCon(15) */
	14,	/* hozAccelLat(14) */
	13,	/* hozAccelLong(13) */
	1,	/* lights(1) */
	19,	/* obDirect(19) */
	18,	/* obDist(18) */
	24,	/* position2D(24) */
	25,	/* position3D(25) */
	8,	/* rainS(8) */
	28,	/* speedC(28) */
	27,	/* speedHeadC(27) */
	4,	/* stab(4) */
	10,	/* steering(10) */
	7,	/* sunS(7) */
	5,	/* trac(5) */
	0,	/* unknown(0) */
	26,	/* vehicle(26) */
	12,	/* vertAccel(12) */
	11,	/* vertAccelThres(11) */
	2,	/* wipers(2) */
	20,	/* yaw(20) */
	21	/* yawRateCon(21) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_DSRC_VehicleStatusDeviceTypeTag_specs_1 = {
	asn_MAP_DSRC_VehicleStatusDeviceTypeTag_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_DSRC_VehicleStatusDeviceTypeTag_enum2value_1,	/* N => "tag"; sorted by N */
	29,	/* Number of elements in the maps */
	30,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_DSRC_VehicleStatusDeviceTypeTag_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_DSRC_VehicleStatusDeviceTypeTag = {
	"DSRC_VehicleStatusDeviceTypeTag",
	"DSRC_VehicleStatusDeviceTypeTag",
	DSRC_VehicleStatusDeviceTypeTag_free,
	DSRC_VehicleStatusDeviceTypeTag_print,
	DSRC_VehicleStatusDeviceTypeTag_constraint,
	DSRC_VehicleStatusDeviceTypeTag_decode_ber,
	DSRC_VehicleStatusDeviceTypeTag_encode_der,
	DSRC_VehicleStatusDeviceTypeTag_decode_xer,
	DSRC_VehicleStatusDeviceTypeTag_encode_xer,
	0, 0,	/* No UPER support, use "-gen-PER" to enable */
	0, 0,	/* No APER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DSRC_VehicleStatusDeviceTypeTag_tags_1,
	sizeof(asn_DEF_DSRC_VehicleStatusDeviceTypeTag_tags_1)
		/sizeof(asn_DEF_DSRC_VehicleStatusDeviceTypeTag_tags_1[0]), /* 1 */
	asn_DEF_DSRC_VehicleStatusDeviceTypeTag_tags_1,	/* Same as above */
	sizeof(asn_DEF_DSRC_VehicleStatusDeviceTypeTag_tags_1)
		/sizeof(asn_DEF_DSRC_VehicleStatusDeviceTypeTag_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_DSRC_VehicleStatusDeviceTypeTag_specs_1	/* Additional specs */
};

