/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_NMEA_Corrections_H_
#define	_DSRC_NMEA_Corrections_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_NMEA-Revision.h"
#include "DSRC_NMEA-MsgType.h"
#include <NativeInteger.h>
#include "DSRC_NMEA-Payload.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_NMEA-Corrections */
typedef struct DSRC_NMEA_Corrections {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_NMEA_Revision_t	 rev;
	DSRC_NMEA_MsgType_t	 msg;
	long	 wdCount;
	DSRC_NMEA_Payload_t	 payload;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_NMEA_Corrections_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_NMEA_Corrections;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_NMEA_Corrections_H_ */
#include <asn_internal.h>
