/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_SirenInUse_H_
#define	_DSRC_SirenInUse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_SirenInUse {
	DSRC_SirenInUse_unavailable	= 0,
	DSRC_SirenInUse_notInUse	= 1,
	DSRC_SirenInUse_inUse	= 2,
	DSRC_SirenInUse_reserved	= 3
} e_DSRC_SirenInUse;

/* DSRC_SirenInUse */
typedef long	 DSRC_SirenInUse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_SirenInUse;
asn_struct_free_f DSRC_SirenInUse_free;
asn_struct_print_f DSRC_SirenInUse_print;
asn_constr_check_f DSRC_SirenInUse_constraint;
ber_type_decoder_f DSRC_SirenInUse_decode_ber;
der_type_encoder_f DSRC_SirenInUse_encode_der;
xer_type_decoder_f DSRC_SirenInUse_decode_xer;
xer_type_encoder_f DSRC_SirenInUse_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_SirenInUse_H_ */
#include <asn_internal.h>
