/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_TransmissionState_H_
#define	_DSRC_TransmissionState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_TransmissionState {
	DSRC_TransmissionState_neutral	= 0,
	DSRC_TransmissionState_park	= 1,
	DSRC_TransmissionState_forwardGears	= 2,
	DSRC_TransmissionState_reverseGears	= 3,
	DSRC_TransmissionState_reserved1	= 4,
	DSRC_TransmissionState_reserved2	= 5,
	DSRC_TransmissionState_reserved3	= 6,
	DSRC_TransmissionState_unavailable	= 7
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_TransmissionState;

/* DSRC_TransmissionState */
typedef long	 DSRC_TransmissionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_TransmissionState;
asn_struct_free_f DSRC_TransmissionState_free;
asn_struct_print_f DSRC_TransmissionState_print;
asn_constr_check_f DSRC_TransmissionState_constraint;
ber_type_decoder_f DSRC_TransmissionState_decode_ber;
der_type_encoder_f DSRC_TransmissionState_encode_der;
xer_type_decoder_f DSRC_TransmissionState_decode_xer;
xer_type_encoder_f DSRC_TransmissionState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_TransmissionState_H_ */
#include <asn_internal.h>
