/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_IntersectionCollision_H_
#define	_DSRC_IntersectionCollision_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_TemporaryID.h"
#include "DSRC_DSecond.h"
#include "DSRC_PathHistory.h"
#include "DSRC_IntersectionID.h"
#include "DSRC_LaneNumber.h"
#include "DSRC_EventFlags.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_IntersectionCollision */
typedef struct DSRC_IntersectionCollision {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	 msgCnt;
	DSRC_TemporaryID_t	 id;
	DSRC_DSecond_t	*secMark	/* OPTIONAL */;
	DSRC_PathHistory_t	 path;
	DSRC_IntersectionID_t	 intersetionID;
	DSRC_LaneNumber_t	 laneNumber;
	DSRC_EventFlags_t	 eventFlag;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_IntersectionCollision_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_IntersectionCollision;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_IntersectionCollision_H_ */
#include <asn_internal.h>
