/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_EmergencyVehicleAlert_H_
#define	_DSRC_EmergencyVehicleAlert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_TemporaryID.h"
#include "DSRC_RoadSideAlert.h"
#include "DSRC_ResponseType.h"
#include "DSRC_EmergencyDetails.h"
#include "DSRC_VehicleMass.h"
#include "DSRC_VehicleType.h"
#include "DSRC_VehicleGroupAffected.h"
#include "DSRC_IncidentResponseEquipment.h"
#include "DSRC_ResponderGroupAffected.h"
#include "DSRC_MsgCRC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_EmergencyVehicleAlert */
typedef struct DSRC_EmergencyVehicleAlert {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_TemporaryID_t	*id	/* OPTIONAL */;
	DSRC_RoadSideAlert_t	 rsaMsg;
	DSRC_ResponseType_t	*responseType	/* OPTIONAL */;
	DSRC_EmergencyDetails_t	*details	/* OPTIONAL */;
	DSRC_VehicleMass_t	*mass	/* OPTIONAL */;
	DSRC_VehicleType_t	*basicType	/* OPTIONAL */;
	DSRC_VehicleGroupAffected_t	*vehicleType	/* OPTIONAL */;
	DSRC_IncidentResponseEquipment_t	*responseEquip	/* OPTIONAL */;
	DSRC_ResponderGroupAffected_t	*responderType	/* OPTIONAL */;
	DSRC_MsgCRC_t	 crc;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_EmergencyVehicleAlert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_EmergencyVehicleAlert;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_EmergencyVehicleAlert_H_ */
#include <asn_internal.h>
