/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_HeadingConfidence_H_
#define	_DSRC_HeadingConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_HeadingConfidence {
	DSRC_HeadingConfidence_unavailable	= 0,
	DSRC_HeadingConfidence_prec45deg	= 1,
	DSRC_HeadingConfidence_prec10deg	= 2,
	DSRC_HeadingConfidence_prec05deg	= 3,
	DSRC_HeadingConfidence_prec01deg	= 4,
	DSRC_HeadingConfidence_prec0_1deg	= 5,
	DSRC_HeadingConfidence_prec0_05deg	= 6,
	DSRC_HeadingConfidence_prec0_01deg	= 7
} e_DSRC_HeadingConfidence;

/* DSRC_HeadingConfidence */
typedef long	 DSRC_HeadingConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_HeadingConfidence;
asn_struct_free_f DSRC_HeadingConfidence_free;
asn_struct_print_f DSRC_HeadingConfidence_print;
asn_constr_check_f DSRC_HeadingConfidence_constraint;
ber_type_decoder_f DSRC_HeadingConfidence_decode_ber;
der_type_encoder_f DSRC_HeadingConfidence_encode_der;
xer_type_decoder_f DSRC_HeadingConfidence_decode_xer;
xer_type_encoder_f DSRC_HeadingConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_HeadingConfidence_H_ */
#include <asn_internal.h>
