/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_SignalRequestMsg_H_
#define	_DSRC_SignalRequestMsg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_SignalRequest.h"
#include "DSRC_DTime.h"
#include "DSRC_TransitStatus.h"
#include "DSRC_VehicleIdent.h"
#include "DSRC_BSMblob.h"
#include "DSRC_VehicleRequestStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_SignalRequestMsg */
typedef struct DSRC_SignalRequestMsg {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	 msgCnt;
	DSRC_SignalRequest_t	 request;
	DSRC_DTime_t	*timeOfService	/* OPTIONAL */;
	DSRC_DTime_t	*endOfService	/* OPTIONAL */;
	DSRC_TransitStatus_t	*transitStatus	/* OPTIONAL */;
	DSRC_VehicleIdent_t	*vehicleVIN	/* OPTIONAL */;
	DSRC_BSMblob_t	 vehicleData;
	DSRC_VehicleRequestStatus_t	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_SignalRequestMsg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_SignalRequestMsg;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_SignalRequestMsg_H_ */
#include <asn_internal.h>
