/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_RoadSignID_H_
#define	_DSRC_RoadSignID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_Position3D.h"
#include "DSRC_HeadingSlice.h"
#include "DSRC_MUTCDCode.h"
#include "DSRC_MsgCRC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_RoadSignID */
typedef struct DSRC_RoadSignID {
	DSRC_Position3D_t	 position;
	DSRC_HeadingSlice_t	 viewAngle;
	DSRC_MUTCDCode_t	*mutcdCode	/* OPTIONAL */;
	DSRC_MsgCRC_t	*crc	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_RoadSignID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_RoadSignID;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_RoadSignID_H_ */
#include <asn_internal.h>
