/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_IncidentResponseEquipment_H_
#define	_DSRC_IncidentResponseEquipment_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_IncidentResponseEquipment {
	DSRC_IncidentResponseEquipment_ground_fire_suppression	= 9985,
	DSRC_IncidentResponseEquipment_heavy_ground_equipment	= 9986,
	DSRC_IncidentResponseEquipment_aircraft	= 9988,
	DSRC_IncidentResponseEquipment_marine_equipment	= 9989,
	DSRC_IncidentResponseEquipment_support_equipment	= 9990,
	DSRC_IncidentResponseEquipment_medical_rescue_unit	= 9991,
	DSRC_IncidentResponseEquipment_other	= 9993,
	DSRC_IncidentResponseEquipment_ground_fire_suppression_other	= 9994,
	DSRC_IncidentResponseEquipment_engine	= 9995,
	DSRC_IncidentResponseEquipment_truck_or_aerial	= 9996,
	DSRC_IncidentResponseEquipment_quint	= 9997,
	DSRC_IncidentResponseEquipment_tanker_pumper_combination	= 9998,
	DSRC_IncidentResponseEquipment_brush_truck	= 10000,
	DSRC_IncidentResponseEquipment_aircraft_rescue_firefighting	= 10001,
	DSRC_IncidentResponseEquipment_heavy_ground_equipment_other	= 10004,
	DSRC_IncidentResponseEquipment_dozer_or_plow	= 10005,
	DSRC_IncidentResponseEquipment_tractor	= 10006,
	DSRC_IncidentResponseEquipment_tanker_or_tender	= 10008,
	DSRC_IncidentResponseEquipment_aircraft_other	= 10024,
	DSRC_IncidentResponseEquipment_aircraft_fixed_wing_tanker	= 10025,
	DSRC_IncidentResponseEquipment_helitanker	= 10026,
	DSRC_IncidentResponseEquipment_helicopter	= 10027,
	DSRC_IncidentResponseEquipment_marine_equipment_other	= 10034,
	DSRC_IncidentResponseEquipment_fire_boat_with_pump	= 10035,
	DSRC_IncidentResponseEquipment_boat_no_pump	= 10036,
	DSRC_IncidentResponseEquipment_support_apparatus_other	= 10044,
	DSRC_IncidentResponseEquipment_breathing_apparatus_support	= 10045,
	DSRC_IncidentResponseEquipment_light_and_air_unit	= 10046,
	DSRC_IncidentResponseEquipment_medical_rescue_unit_other	= 10054,
	DSRC_IncidentResponseEquipment_rescue_unit	= 10055,
	DSRC_IncidentResponseEquipment_urban_search_rescue_unit	= 10056,
	DSRC_IncidentResponseEquipment_high_angle_rescue	= 10057,
	DSRC_IncidentResponseEquipment_crash_fire_rescue	= 10058,
	DSRC_IncidentResponseEquipment_bLS_unit	= 10059,
	DSRC_IncidentResponseEquipment_aLS_unit	= 10060,
	DSRC_IncidentResponseEquipment_mobile_command_post	= 10075,
	DSRC_IncidentResponseEquipment_chief_officer_car	= 10076,
	DSRC_IncidentResponseEquipment_hAZMAT_unit	= 10077,
	DSRC_IncidentResponseEquipment_type_i_hand_crew	= 10078,
	DSRC_IncidentResponseEquipment_type_ii_hand_crew	= 10079,
	DSRC_IncidentResponseEquipment_privately_owned_vehicle	= 10083,
	DSRC_IncidentResponseEquipment_other_apparatus_resource	= 10084,
	DSRC_IncidentResponseEquipment_ambulance	= 10085,
	DSRC_IncidentResponseEquipment_bomb_squad_van	= 10086,
	DSRC_IncidentResponseEquipment_combine_harvester	= 10087,
	DSRC_IncidentResponseEquipment_construction_vehicle	= 10088,
	DSRC_IncidentResponseEquipment_farm_tractor	= 10089,
	DSRC_IncidentResponseEquipment_grass_cutting_machines	= 10090,
	DSRC_IncidentResponseEquipment_hAZMAT_containment_tow	= 10091,
	DSRC_IncidentResponseEquipment_heavy_tow	= 10092,
	DSRC_IncidentResponseEquipment_light_tow	= 10094,
	DSRC_IncidentResponseEquipment_flatbed_tow	= 10114,
	DSRC_IncidentResponseEquipment_hedge_cutting_machines	= 10093,
	DSRC_IncidentResponseEquipment_mobile_crane	= 10095,
	DSRC_IncidentResponseEquipment_refuse_collection_vehicle	= 10096,
	DSRC_IncidentResponseEquipment_resurfacing_vehicle	= 10097,
	DSRC_IncidentResponseEquipment_road_sweeper	= 10098,
	DSRC_IncidentResponseEquipment_roadside_litter_collection_crews	= 10099,
	DSRC_IncidentResponseEquipment_salvage_vehicle	= 10100,
	DSRC_IncidentResponseEquipment_sand_truck	= 10101,
	DSRC_IncidentResponseEquipment_snowplow	= 10102,
	DSRC_IncidentResponseEquipment_steam_roller	= 10103,
	DSRC_IncidentResponseEquipment_swat_team_van	= 10104,
	DSRC_IncidentResponseEquipment_track_laying_vehicle	= 10105,
	DSRC_IncidentResponseEquipment_unknown_vehicle	= 10106,
	DSRC_IncidentResponseEquipment_white_lining_vehicle	= 10107,
	DSRC_IncidentResponseEquipment_dump_truck	= 10108,
	DSRC_IncidentResponseEquipment_supervisor_vehicle	= 10109,
	DSRC_IncidentResponseEquipment_snow_blower	= 10110,
	DSRC_IncidentResponseEquipment_rotary_snow_blower	= 10111,
	DSRC_IncidentResponseEquipment_road_grader	= 10112,
	DSRC_IncidentResponseEquipment_steam_truck	= 10113
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_IncidentResponseEquipment;

/* DSRC_IncidentResponseEquipment */
typedef long	 DSRC_IncidentResponseEquipment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_IncidentResponseEquipment;
asn_struct_free_f DSRC_IncidentResponseEquipment_free;
asn_struct_print_f DSRC_IncidentResponseEquipment_print;
asn_constr_check_f DSRC_IncidentResponseEquipment_constraint;
ber_type_decoder_f DSRC_IncidentResponseEquipment_decode_ber;
der_type_encoder_f DSRC_IncidentResponseEquipment_encode_der;
xer_type_decoder_f DSRC_IncidentResponseEquipment_decode_xer;
xer_type_encoder_f DSRC_IncidentResponseEquipment_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_IncidentResponseEquipment_H_ */
#include <asn_internal.h>
