/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_PathHistory_H_
#define	_DSRC_PathHistory_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_FullPositionVector.h"
#include "DSRC_GPSstatus.h"
#include "DSRC_Count.h"
#include <OCTET_STRING.h>
#include "DSRC_PathHistoryPointType-01.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_PathHistory__crumbData_PR {
	DSRC_PathHistory__crumbData_PR_NOTHING,	/* No components present */
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_01,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_02,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_03,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_04,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_05,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_06,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_07,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_08,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_09,
	DSRC_PathHistory__crumbData_PR_pathHistoryPointSets_10
} DSRC_PathHistory__crumbData_PR;

/* DSRC_PathHistory */
typedef struct DSRC_PathHistory {
	DSRC_FullPositionVector_t	*initialPosition	/* OPTIONAL */;
	DSRC_GPSstatus_t	*currGPSstatus	/* OPTIONAL */;
	DSRC_Count_t	*itemCnt	/* OPTIONAL */;
	struct DSRC_PathHistory__crumbData {
		DSRC_PathHistory__crumbData_PR present;
		union DSRC_PathHistory__crumbData_u {
			struct DSRC_PathHistory__crumbData__pathHistoryPointSets_01 {
				A_SEQUENCE_OF(DSRC_PathHistoryPointType_01_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} pathHistoryPointSets_01;
			OCTET_STRING_t	 pathHistoryPointSets_02;
			OCTET_STRING_t	 pathHistoryPointSets_03;
			OCTET_STRING_t	 pathHistoryPointSets_04;
			OCTET_STRING_t	 pathHistoryPointSets_05;
			OCTET_STRING_t	 pathHistoryPointSets_06;
			OCTET_STRING_t	 pathHistoryPointSets_07;
			OCTET_STRING_t	 pathHistoryPointSets_08;
			OCTET_STRING_t	 pathHistoryPointSets_09;
			OCTET_STRING_t	 pathHistoryPointSets_10;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} crumbData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_PathHistory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_PathHistory;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_PathHistory_H_ */
#include <asn_internal.h>
