/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_MapData_H_
#define	_DSRC_MapData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_DescriptiveName.h"
#include "DSRC_LayerType.h"
#include "DSRC_LayerID.h"
#include "DSRC_DataParameters.h"
#include "DSRC_MsgCRC.h"
#include "DSRC_Intersection.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_MapData */
typedef struct DSRC_MapData {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	 msgCnt;
	DSRC_DescriptiveName_t	*name	/* OPTIONAL */;
	DSRC_LayerType_t	*layerType	/* OPTIONAL */;
	DSRC_LayerID_t	*layerID	/* OPTIONAL */;
	struct DSRC_MapData__intersections {
		A_SEQUENCE_OF(DSRC_Intersection_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *intersections;
	DSRC_DataParameters_t	*dataParameters	/* OPTIONAL */;
	DSRC_MsgCRC_t	 crc;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_MapData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_MapData;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_MapData_H_ */
#include <asn_internal.h>
