/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_WheelEndElectFault_H_
#define	_DSRC_WheelEndElectFault_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_WheelEndElectFault {
	DSRC_WheelEndElectFault_bitOne	= 1,
	DSRC_WheelEndElectFault_bitTwo	= 2,
	DSRC_WheelEndElectFault_bitThree	= 3,
	DSRC_WheelEndElectFault_bitFour	= 4
} e_DSRC_WheelEndElectFault;

/* DSRC_WheelEndElectFault */
typedef BIT_STRING_t	 DSRC_WheelEndElectFault_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_WheelEndElectFault;
asn_struct_free_f DSRC_WheelEndElectFault_free;
asn_struct_print_f DSRC_WheelEndElectFault_print;
asn_constr_check_f DSRC_WheelEndElectFault_constraint;
ber_type_decoder_f DSRC_WheelEndElectFault_decode_ber;
der_type_encoder_f DSRC_WheelEndElectFault_encode_der;
xer_type_decoder_f DSRC_WheelEndElectFault_decode_xer;
xer_type_encoder_f DSRC_WheelEndElectFault_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_WheelEndElectFault_H_ */
#include <asn_internal.h>
