/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_ProbeDataManagement_H_
#define	_DSRC_ProbeDataManagement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_Sample.h"
#include "DSRC_HeadingSlice.h"
#include "DSRC_TxTime.h"
#include "DSRC_Count.h"
#include "DSRC_TermTime.h"
#include "DSRC_TermDistance.h"
#include <constr_CHOICE.h>
#include "DSRC_SnapshotTime.h"
#include "DSRC_SnapshotDistance.h"
#include "DSRC_VehicleStatusRequest.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_ProbeDataManagement__term_PR {
	DSRC_ProbeDataManagement__term_PR_NOTHING,	/* No components present */
	DSRC_ProbeDataManagement__term_PR_termtime,
	DSRC_ProbeDataManagement__term_PR_termDistance
} DSRC_ProbeDataManagement__term_PR;
typedef enum DSRC_ProbeDataManagement__snapshot_PR {
	DSRC_ProbeDataManagement__snapshot_PR_NOTHING,	/* No components present */
	DSRC_ProbeDataManagement__snapshot_PR_snapshotTime,
	DSRC_ProbeDataManagement__snapshot_PR_snapshotDistance
} DSRC_ProbeDataManagement__snapshot_PR;

/* DSRC_ProbeDataManagement */
typedef struct DSRC_ProbeDataManagement {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_Sample_t	 sample;
	DSRC_HeadingSlice_t	 directions;
	struct DSRC_ProbeDataManagement__term {
		DSRC_ProbeDataManagement__term_PR present;
		union DSRC_ProbeDataManagement__term_u {
			DSRC_TermTime_t	 termtime;
			DSRC_TermDistance_t	 termDistance;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} term;
	struct DSRC_ProbeDataManagement__snapshot {
		DSRC_ProbeDataManagement__snapshot_PR present;
		union DSRC_ProbeDataManagement__snapshot_u {
			DSRC_SnapshotTime_t	 snapshotTime;
			DSRC_SnapshotDistance_t	 snapshotDistance;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} snapshot;
	DSRC_TxTime_t	 txInterval;
	DSRC_Count_t	 cntTthreshold;
	struct DSRC_ProbeDataManagement__dataElements {
		A_SEQUENCE_OF(DSRC_VehicleStatusRequest_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dataElements;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_ProbeDataManagement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_ProbeDataManagement;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_ProbeDataManagement_H_ */
#include <asn_internal.h>
