/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_Snapshot_H_
#define	_DSRC_Snapshot_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_FullPositionVector.h"
#include "DSRC_VehicleSafetyExtension.h"
#include "DSRC_VehicleStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_Snapshot */
typedef struct DSRC_Snapshot {
	DSRC_FullPositionVector_t	 thePosition;
	DSRC_VehicleSafetyExtension_t	*safetyExt	/* OPTIONAL */;
	DSRC_VehicleStatus_t	*datSet	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_Snapshot_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_Snapshot;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_Snapshot_H_ */
#include <asn_internal.h>
