/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_BasicSafetyMessageVerbose_H_
#define	_DSRC_BasicSafetyMessageVerbose_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_TemporaryID.h"
#include "DSRC_DSecond.h"
#include "DSRC_Latitude.h"
#include "DSRC_Longitude.h"
#include "DSRC_Elevation.h"
#include "DSRC_PositionalAccuracy.h"
#include "DSRC_TransmissionAndSpeed.h"
#include "DSRC_Heading.h"
#include "DSRC_SteeringWheelAngle.h"
#include "DSRC_AccelerationSet4Way.h"
#include "DSRC_BrakeSystemStatus.h"
#include "DSRC_VehicleSize.h"
#include "DSRC_VehicleSafetyExtension.h"
#include "DSRC_VehicleStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_BasicSafetyMessageVerbose */
typedef struct DSRC_BasicSafetyMessageVerbose {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	 msgCnt;
	DSRC_TemporaryID_t	 id;
	DSRC_DSecond_t	 secMark;
	DSRC_Latitude_t	 lat;
	DSRC_Longitude_t	 Long;
	DSRC_Elevation_t	 elev;
	DSRC_PositionalAccuracy_t	 accuracy;
	DSRC_TransmissionAndSpeed_t	 speed;
	DSRC_Heading_t	 heading;
	DSRC_SteeringWheelAngle_t	 angle;
	DSRC_AccelerationSet4Way_t	 accelSet;
	DSRC_BrakeSystemStatus_t	 brakes;
	DSRC_VehicleSize_t	 size;
	DSRC_VehicleSafetyExtension_t	*safetyExt	/* OPTIONAL */;
	DSRC_VehicleStatus_t	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_BasicSafetyMessageVerbose_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_BasicSafetyMessageVerbose;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_BasicSafetyMessageVerbose_H_ */
#include <asn_internal.h>
