/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_Intersection_H_
#define	_DSRC_Intersection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DescriptiveName.h"
#include "DSRC_IntersectionID.h"
#include "DSRC_Position3D.h"
#include "DSRC_Heading.h"
#include "DSRC_LaneWidth.h"
#include "DSRC_IntersectionStatusObject.h"
#include "DSRC_ApproachObject.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "DSRC_SignalControlZone.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_Intersection */
typedef struct DSRC_Intersection {
	DSRC_DescriptiveName_t	*name	/* OPTIONAL */;
	DSRC_IntersectionID_t	 id;
	DSRC_Position3D_t	*refPoint	/* OPTIONAL */;
	DSRC_IntersectionID_t	*refInterNum	/* OPTIONAL */;
	DSRC_Heading_t	*orientation	/* OPTIONAL */;
	DSRC_LaneWidth_t	*laneWidth	/* OPTIONAL */;
	DSRC_IntersectionStatusObject_t	*type	/* OPTIONAL */;
	struct DSRC_Intersection__approaches {
		A_SEQUENCE_OF(DSRC_ApproachObject_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} approaches;
	struct DSRC_Intersection__preemptZones {
		A_SEQUENCE_OF(DSRC_SignalControlZone_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *preemptZones;
	struct DSRC_Intersection__priorityZones {
		A_SEQUENCE_OF(DSRC_SignalControlZone_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *priorityZones;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_Intersection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_Intersection;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_Intersection_H_ */
#include <asn_internal.h>
