/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_SignalStatusMessage_H_
#define	_DSRC_SignalStatusMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_IntersectionID.h"
#include "DSRC_IntersectionStatusObject.h"
#include "DSRC_VehicleIdent.h"
#include "DSRC_TransitStatus.h"
#include "DSRC_SignalState.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_SignalStatusMessage */
typedef struct DSRC_SignalStatusMessage {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	 msgCnt;
	DSRC_IntersectionID_t	 id;
	DSRC_IntersectionStatusObject_t	 status;
	struct DSRC_SignalStatusMessage__priority {
		A_SEQUENCE_OF(DSRC_SignalState_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *priority;
	DSRC_VehicleIdent_t	*priorityCause	/* OPTIONAL */;
	struct DSRC_SignalStatusMessage__prempt {
		A_SEQUENCE_OF(DSRC_SignalState_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *prempt;
	DSRC_VehicleIdent_t	*preemptCause	/* OPTIONAL */;
	DSRC_TransitStatus_t	*transitStatus	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_SignalStatusMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_SignalStatusMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_SignalStatusMessage_H_ */
#include <asn_internal.h>
