/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_NMEA_Revision_H_
#define	_DSRC_NMEA_Revision_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_NMEA_Revision {
	DSRC_NMEA_Revision_unknown	= 0,
	DSRC_NMEA_Revision_reserved	= 1,
	DSRC_NMEA_Revision_rev1	= 10,
	DSRC_NMEA_Revision_rev2	= 20,
	DSRC_NMEA_Revision_rev3	= 30,
	DSRC_NMEA_Revision_rev4	= 40,
	DSRC_NMEA_Revision_rev5	= 50
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_NMEA_Revision;

/* DSRC_NMEA-Revision */
typedef long	 DSRC_NMEA_Revision_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_NMEA_Revision;
asn_struct_free_f DSRC_NMEA_Revision_free;
asn_struct_print_f DSRC_NMEA_Revision_print;
asn_constr_check_f DSRC_NMEA_Revision_constraint;
ber_type_decoder_f DSRC_NMEA_Revision_decode_ber;
der_type_encoder_f DSRC_NMEA_Revision_encode_der;
xer_type_decoder_f DSRC_NMEA_Revision_decode_xer;
xer_type_encoder_f DSRC_NMEA_Revision_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_NMEA_Revision_H_ */
#include <asn_internal.h>
