/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_Location_quality_H_
#define	_DSRC_Location_quality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_Location_quality {
	DSRC_Location_quality_loc_qual_bt1m	= 0,
	DSRC_Location_quality_loc_qual_bt5m	= 1,
	DSRC_Location_quality_loc_qual_bt12m	= 2,
	DSRC_Location_quality_loc_qual_bt50m	= 3,
	DSRC_Location_quality_loc_qual_bt125m	= 4,
	DSRC_Location_quality_loc_qual_bt500m	= 5,
	DSRC_Location_quality_loc_qual_bt1250m	= 6,
	DSRC_Location_quality_loc_qual_unknown	= 7
} e_DSRC_Location_quality;

/* DSRC_Location-quality */
typedef long	 DSRC_Location_quality_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_Location_quality;
asn_struct_free_f DSRC_Location_quality_free;
asn_struct_print_f DSRC_Location_quality_print;
asn_constr_check_f DSRC_Location_quality_constraint;
ber_type_decoder_f DSRC_Location_quality_decode_ber;
der_type_encoder_f DSRC_Location_quality_encode_der;
xer_type_decoder_f DSRC_Location_quality_decode_xer;
xer_type_encoder_f DSRC_Location_quality_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_Location_quality_H_ */
#include <asn_internal.h>
