/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_TimeConfidence_H_
#define	_DSRC_TimeConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_TimeConfidence {
	DSRC_TimeConfidence_unavailable	= 0,
	DSRC_TimeConfidence_time_100_000	= 1,
	DSRC_TimeConfidence_time_050_000	= 2,
	DSRC_TimeConfidence_time_020_000	= 3,
	DSRC_TimeConfidence_time_010_000	= 4,
	DSRC_TimeConfidence_time_002_000	= 5,
	DSRC_TimeConfidence_time_001_000	= 6,
	DSRC_TimeConfidence_time_000_500	= 7,
	DSRC_TimeConfidence_time_000_200	= 8,
	DSRC_TimeConfidence_time_000_100	= 9,
	DSRC_TimeConfidence_time_000_050	= 10,
	DSRC_TimeConfidence_time_000_020	= 11,
	DSRC_TimeConfidence_time_000_010	= 12,
	DSRC_TimeConfidence_time_000_005	= 13,
	DSRC_TimeConfidence_time_000_002	= 14,
	DSRC_TimeConfidence_time_000_001	= 15,
	DSRC_TimeConfidence_time_000_000_5	= 16,
	DSRC_TimeConfidence_time_000_000_2	= 17,
	DSRC_TimeConfidence_time_000_000_1	= 18,
	DSRC_TimeConfidence_time_000_000_05	= 19,
	DSRC_TimeConfidence_time_000_000_02	= 20,
	DSRC_TimeConfidence_time_000_000_01	= 21,
	DSRC_TimeConfidence_time_000_000_005	= 22,
	DSRC_TimeConfidence_time_000_000_002	= 23,
	DSRC_TimeConfidence_time_000_000_001	= 24,
	DSRC_TimeConfidence_time_000_000_000_5	= 25,
	DSRC_TimeConfidence_time_000_000_000_2	= 26,
	DSRC_TimeConfidence_time_000_000_000_1	= 27,
	DSRC_TimeConfidence_time_000_000_000_05	= 28,
	DSRC_TimeConfidence_time_000_000_000_02	= 29,
	DSRC_TimeConfidence_time_000_000_000_01	= 30,
	DSRC_TimeConfidence_time_000_000_000_005	= 31,
	DSRC_TimeConfidence_time_000_000_000_002	= 32,
	DSRC_TimeConfidence_time_000_000_000_001	= 33,
	DSRC_TimeConfidence_time_000_000_000_000_5	= 34,
	DSRC_TimeConfidence_time_000_000_000_000_2	= 35,
	DSRC_TimeConfidence_time_000_000_000_000_1	= 36,
	DSRC_TimeConfidence_time_000_000_000_000_05	= 37,
	DSRC_TimeConfidence_time_000_000_000_000_02	= 38,
	DSRC_TimeConfidence_time_000_000_000_000_01	= 39
} e_DSRC_TimeConfidence;

/* DSRC_TimeConfidence */
typedef long	 DSRC_TimeConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_TimeConfidence;
asn_struct_free_f DSRC_TimeConfidence_free;
asn_struct_print_f DSRC_TimeConfidence_print;
asn_constr_check_f DSRC_TimeConfidence_constraint;
ber_type_decoder_f DSRC_TimeConfidence_decode_ber;
der_type_encoder_f DSRC_TimeConfidence_encode_der;
xer_type_decoder_f DSRC_TimeConfidence_decode_xer;
xer_type_encoder_f DSRC_TimeConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_TimeConfidence_H_ */
#include <asn_internal.h>
