/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_PriorityState_H_
#define	_DSRC_PriorityState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_PriorityState {
	DSRC_PriorityState_noneActive	= 0,
	DSRC_PriorityState_none	= 1,
	DSRC_PriorityState_requested	= 2,
	DSRC_PriorityState_active	= 3,
	DSRC_PriorityState_activeButIhibitd	= 4,
	DSRC_PriorityState_seccess	= 5,
	DSRC_PriorityState_removed	= 6,
	DSRC_PriorityState_clearFail	= 7,
	DSRC_PriorityState_detectFail	= 8,
	DSRC_PriorityState_detectClear	= 9,
	DSRC_PriorityState_abort	= 10,
	DSRC_PriorityState_delayTiming	= 11,
	DSRC_PriorityState_extendTiming	= 12,
	DSRC_PriorityState_preemptOverride	= 13,
	DSRC_PriorityState_adaptiveOverride	= 14,
	DSRC_PriorityState_reserved	= 15
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_PriorityState;

/* DSRC_PriorityState */
typedef long	 DSRC_PriorityState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_PriorityState;
asn_struct_free_f DSRC_PriorityState_free;
asn_struct_print_f DSRC_PriorityState_print;
asn_constr_check_f DSRC_PriorityState_constraint;
ber_type_decoder_f DSRC_PriorityState_decode_ber;
der_type_encoder_f DSRC_PriorityState_encode_der;
xer_type_decoder_f DSRC_PriorityState_decode_xer;
xer_type_encoder_f DSRC_PriorityState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_PriorityState_H_ */
#include <asn_internal.h>
