/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_AllInclusive_H_
#define	_DSRC_AllInclusive_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_AccelerationSet4Way.h"
#include "DSRC_AccelSteerYawRateConfidence.h"
#include "DSRC_AntennaOffsetSet.h"
#include "DSRC_Approach.h"
#include "DSRC_ApproachObject.h"
#include "DSRC_BarrierLane.h"
#include "DSRC_BrakeSystemStatus.h"
#include "DSRC_BSMblob.h"
#include "DSRC_BumperHeights.h"
#include "DSRC_Circle.h"
#include "DSRC_ConfidenceSet.h"
#include "DSRC_ConnectsTo.h"
#include "DSRC_CrosswalkLane.h"
#include "DSRC_DataParameters.h"
#include "DSRC_DDate.h"
#include "DSRC_DDateTime.h"
#include "DSRC_DFullTime.h"
#include "DSRC_DMonthDay.h"
#include "DSRC_DTime.h"
#include "DSRC_DYearMonth.h"
#include "DSRC_FullPositionVector.h"
#include "DSRC_Intersection.h"
#include "DSRC_IntersectionState.h"
#include "DSRC_ExitService.h"
#include "DSRC_GenericSignage.h"
#include "DSRC_SpeedLimit.h"
#include "DSRC_WorkZone.h"
#include "DSRC_J1939data.h"
#include "DSRC_MovementState.h"
#include "DSRC_NodeList.h"
#include "DSRC_Offsets.h"
#include "DSRC_PathHistory.h"
#include "DSRC_PathHistoryPointType-01.h"
#include "DSRC_PathHistoryPointType-02.h"
#include "DSRC_PathHistoryPointType-03.h"
#include "DSRC_PathHistoryPointType-04.h"
#include "DSRC_PathHistoryPointType-05.h"
#include "DSRC_PathHistoryPointType-06.h"
#include "DSRC_PathHistoryPointType-07.h"
#include "DSRC_PathHistoryPointType-08.h"
#include "DSRC_PathHistoryPointType-09.h"
#include "DSRC_PathHistoryPointType-10.h"
#include "DSRC_PathPrediction.h"
#include "DSRC_Position3D.h"
#include "DSRC_PositionalAccuracy.h"
#include "DSRC_PositionConfidenceSet.h"
#include "DSRC_RegionList.h"
#include "DSRC_RegionOffsets.h"
#include "DSRC_RegionPointSet.h"
#include "DSRC_RoadSignID.h"
#include "DSRC_RTCMHeader.h"
#include "DSRC_RTCMmsg.h"
#include "DSRC_RTCMPackage.h"
#include "DSRC_Sample.h"
#include "DSRC_ShapePointSet.h"
#include "DSRC_SignalControlZone.h"
#include "DSRC_SignalRequest.h"
#include "DSRC_SnapshotDistance.h"
#include "DSRC_Snapshot.h"
#include "DSRC_SnapshotTime.h"
#include "DSRC_SpecialLane.h"
#include "DSRC_SpeedandHeadingandThrottleConfidence.h"
#include "DSRC_TransmissionAndSpeed.h"
#include "DSRC_ValidRegion.h"
#include "DSRC_VehicleComputedLane.h"
#include "DSRC_VehicleIdent.h"
#include "DSRC_VehicleReferenceLane.h"
#include "DSRC_VehicleSafetyExtension.h"
#include "DSRC_VehicleSize.h"
#include "DSRC_VehicleStatusRequest.h"
#include "DSRC_VehicleStatus.h"
#include "DSRC_WiperStatus.h"
#include "DSRC_Acceleration.h"
#include "DSRC_AccelerationConfidence.h"
#include "DSRC_AmbientAirPressure.h"
#include "DSRC_AmbientAirTemperature.h"
#include "DSRC_AntiLockBrakeStatus.h"
#include "DSRC_ApproachNumber.h"
#include "DSRC_AuxiliaryBrakeStatus.h"
#include "DSRC_BarrierAttributes.h"
#include "DSRC_BrakeAppliedPressure.h"
#include "DSRC_BrakeAppliedStatus.h"
#include "DSRC_BrakeBoostApplied.h"
#include "DSRC_BumperHeightFront.h"
#include "DSRC_BumperHeightRear.h"
#include "DSRC_CodeWord.h"
#include "DSRC_CoefficientOfFriction.h"
#include "DSRC_ColorState.h"
#include "DSRC_Count.h"
#include "DSRC_CrosswalkLaneAttributes.h"
#include "DSRC_DDay.h"
#include "DSRC_DescriptiveName.h"
#include "DSRC_DHour.h"
#include "DSRC_DirectionOfUse.h"
#include "DSRC_DMinute.h"
#include "DSRC_DMonth.h"
#include "DSRC_DOffset.h"
#include "DSRC_DrivenLineOffset.h"
#include "DSRC_DrivingWheelAngle.h"
#include "DSRC_DSecond.h"
#include "DSRC_DSignalSeconds.h"
#include "DSRC_DSRCmsgID.h"
#include "DSRC_DYear.h"
#include "DSRC_ElevationConfidence.h"
#include "DSRC_Elevation.h"
#include "DSRC_EmergencyDetails.h"
#include "DSRC_EventFlags.h"
#include "DSRC_Extent.h"
#include "DSRC_ExteriorLights.h"
#include "DSRC_FurtherInfoID.h"
#include "DSRC_GPSstatus.h"
#include "DSRC_HeadingConfidence.h"
#include "DSRC_Heading.h"
#include "DSRC_HeadingSlice.h"
#include "DSRC_IntersectionStatusObject.h"
#include "DSRC_IntersectionID.h"
#include "DSRC_AxleLocation.h"
#include "DSRC_AxleWeight.h"
#include "DSRC_CargoWeight.h"
#include "DSRC_DriveAxleLiftAirPressure.h"
#include "DSRC_DriveAxleLocation.h"
#include "DSRC_DriveAxleLubePressure.h"
#include "DSRC_DriveAxleTemperature.h"
#include "DSRC_SteeringAxleLubePressure.h"
#include "DSRC_SteeringAxleTemperature.h"
#include "DSRC_TireLeakageRate.h"
#include "DSRC_TireLocation.h"
#include "DSRC_TirePressureThresholdDetection.h"
#include "DSRC_TirePressure.h"
#include "DSRC_TireTemp.h"
#include "DSRC_TrailerWeight.h"
#include "DSRC_WheelEndElectFault.h"
#include "DSRC_WheelSensorStatus.h"
#include "DSRC_LaneCount.h"
#include "DSRC_LaneManeuverCode.h"
#include "DSRC_LaneNumber.h"
#include "DSRC_LaneSet.h"
#include "DSRC_LaneWidth.h"
#include "DSRC_Latitude.h"
#include "DSRC_LayerID.h"
#include "DSRC_LayerType.h"
#include "DSRC_LightbarInUse.h"
#include "DSRC_Longitude.h"
#include "DSRC_Location-quality.h"
#include "DSRC_Location-tech.h"
#include "DSRC_MinuteOfTheYear.h"
#include "DSRC_MinutesDuration.h"
#include "DSRC_MsgCount.h"
#include "DSRC_MsgCRC.h"
#include "DSRC_MultiVehicleResponse.h"
#include "DSRC_MUTCDCode.h"
#include "DSRC_NMEA-MsgType.h"
#include "DSRC_NMEA-Payload.h"
#include "DSRC_NMEA-Revision.h"
#include "DSRC_NTCIPVehicleclass.h"
#include "DSRC_ObjectCount.h"
#include "DSRC_ObstacleDirection.h"
#include "DSRC_ObstacleDistance.h"
#include "DSRC_PayloadData.h"
#include "DSRC_Payload.h"
#include "DSRC_PedestrianDetect.h"
#include "DSRC_PedestrianSignalState.h"
#include "DSRC_PositionConfidence.h"
#include "DSRC_PreemptState.h"
#include "DSRC_Priority.h"
#include "DSRC_PriorityState.h"
#include "DSRC_ProbeSegmentNumber.h"
#include "DSRC_RainSensor.h"
#include "DSRC_RequestedItem.h"
#include "DSRC_ResponseType.h"
#include "DSRC_RTCM-ID.h"
#include "DSRC_RTCM-Payload.h"
#include "DSRC_RTCM-Revision.h"
#include "DSRC_SignalLightState.h"
#include "DSRC_SignalReqScheme.h"
#include "DSRC_SignalState.h"
#include "DSRC_SignPrority.h"
#include "DSRC_SirenInUse.h"
#include "DSRC_SpecialLaneAttributes.h"
#include "DSRC_SpecialSignalState.h"
#include "DSRC_SpeedConfidence.h"
#include "DSRC_Speed.h"
#include "DSRC_StabilityControlStatus.h"
#include "DSRC_StateConfidence.h"
#include "DSRC_SteeringWheelAngleConfidence.h"
#include "DSRC_SteeringWheelAngleRateOfChange.h"
#include "DSRC_SteeringWheelAngle.h"
#include "DSRC_SunSensor.h"
#include "DSRC_TemporaryID.h"
#include "DSRC_TermDistance.h"
#include "DSRC_TermTime.h"
#include "DSRC_ThrottleConfidence.h"
#include "DSRC_ThrottlePosition.h"
#include "DSRC_TimeConfidence.h"
#include "DSRC_TimeMark.h"
#include "DSRC_TractionControlState.h"
#include "DSRC_TransitPreEmptionRequest.h"
#include "DSRC_TransitStatus.h"
#include "DSRC_TransmissionState.h"
#include "DSRC_TxTime.h"
#include "DSRC_TravelerInfoType.h"
#include "DSRC_UniqueMSGID.h"
#include "DSRC_URL-Base.h"
#include "DSRC_URL-Link.h"
#include "DSRC_URL-Short.h"
#include "DSRC_VehicleHeight.h"
#include "DSRC_VehicleLaneAttributes.h"
#include "DSRC_VehicleLength.h"
#include "DSRC_VehicleMass.h"
#include "DSRC_VehicleRequestStatus.h"
#include "DSRC_VehicleStatusDeviceTypeTag.h"
#include "DSRC_VehicleType.h"
#include "DSRC_VehicleWidth.h"
#include "DSRC_VerticalAccelerationThreshold.h"
#include "DSRC_VerticalAcceleration.h"
#include "DSRC_VINstring.h"
#include "DSRC_WiperRate.h"
#include "DSRC_WiperStatusFront.h"
#include "DSRC_WiperStatusRear.h"
#include "DSRC_YawRateConfidence.h"
#include "DSRC_YawRate.h"
#include "DSRC_IncidentResponseEquipment.h"
#include "DSRC_ITIStext.h"
#include "DSRC_ResponderGroupAffected.h"
#include "DSRC_VehicleGroupAffected.h"
#include "DSRC_ITIScodesAndText.h"
#include "DSRC_EssMobileFriction.h"
#include "DSRC_EssPrecipRate.h"
#include "DSRC_EssPrecipSituation.h"
#include "DSRC_EssPrecipYesNo.h"
#include "DSRC_EssSolarRadiation.h"
#include "DSRC_ITIScodes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_AllInclusive */
typedef struct DSRC_AllInclusive {
	DSRC_AccelerationSet4Way_t	*item6_1	/* OPTIONAL */;
	DSRC_AccelSteerYawRateConfidence_t	*item6_2	/* OPTIONAL */;
	DSRC_AntennaOffsetSet_t	*item6_4	/* OPTIONAL */;
	DSRC_Approach_t	*item6_5	/* OPTIONAL */;
	DSRC_ApproachObject_t	*item6_6	/* OPTIONAL */;
	DSRC_BarrierLane_t	*item6_7	/* OPTIONAL */;
	DSRC_BrakeSystemStatus_t	*item6_8	/* OPTIONAL */;
	DSRC_BSMblob_t	*item6_9	/* OPTIONAL */;
	DSRC_BumperHeights_t	*item6_10	/* OPTIONAL */;
	DSRC_Circle_t	*item6_11	/* OPTIONAL */;
	DSRC_ConfidenceSet_t	*item6_12	/* OPTIONAL */;
	DSRC_ConnectsTo_t	*item6_13	/* OPTIONAL */;
	DSRC_CrosswalkLane_t	*item6_14	/* OPTIONAL */;
	DSRC_DataParameters_t	*item6_15	/* OPTIONAL */;
	DSRC_DDate_t	*item6_16	/* OPTIONAL */;
	DSRC_DDateTime_t	*item6_17	/* OPTIONAL */;
	DSRC_DFullTime_t	*item6_18	/* OPTIONAL */;
	DSRC_DMonthDay_t	*item6_19	/* OPTIONAL */;
	DSRC_DTime_t	*item6_20	/* OPTIONAL */;
	DSRC_DYearMonth_t	*item6_21	/* OPTIONAL */;
	DSRC_FullPositionVector_t	*item6_22	/* OPTIONAL */;
	DSRC_Intersection_t	*item6_23	/* OPTIONAL */;
	DSRC_IntersectionState_t	*item6_24	/* OPTIONAL */;
	DSRC_ExitService_t	*item6_25	/* OPTIONAL */;
	DSRC_GenericSignage_t	*item6_26	/* OPTIONAL */;
	DSRC_SpeedLimit_t	*item6_27	/* OPTIONAL */;
	DSRC_WorkZone_t	*item6_28	/* OPTIONAL */;
	DSRC_J1939data_t	*item6_29	/* OPTIONAL */;
	DSRC_MovementState_t	*item6_30	/* OPTIONAL */;
	DSRC_NodeList_t	*item6_31	/* OPTIONAL */;
	DSRC_Offsets_t	*item6_32	/* OPTIONAL */;
	DSRC_PathHistory_t	*item6_33	/* OPTIONAL */;
	DSRC_PathHistoryPointType_01_t	*item6_34	/* OPTIONAL */;
	DSRC_PathHistoryPointType_02_t	*item6_35	/* OPTIONAL */;
	DSRC_PathHistoryPointType_03_t	*item6_36	/* OPTIONAL */;
	DSRC_PathHistoryPointType_04_t	*item6_37	/* OPTIONAL */;
	DSRC_PathHistoryPointType_05_t	*item6_38	/* OPTIONAL */;
	DSRC_PathHistoryPointType_06_t	*item6_39	/* OPTIONAL */;
	DSRC_PathHistoryPointType_07_t	*item6_40	/* OPTIONAL */;
	DSRC_PathHistoryPointType_08_t	*item6_41	/* OPTIONAL */;
	DSRC_PathHistoryPointType_09_t	*item6_42	/* OPTIONAL */;
	DSRC_PathHistoryPointType_10_t	*item6_43	/* OPTIONAL */;
	DSRC_PathPrediction_t	*item6_44	/* OPTIONAL */;
	DSRC_Position3D_t	*item6_45	/* OPTIONAL */;
	DSRC_PositionalAccuracy_t	*item6_46	/* OPTIONAL */;
	DSRC_PositionConfidenceSet_t	*item6_47	/* OPTIONAL */;
	DSRC_RegionList_t	*item6_48	/* OPTIONAL */;
	DSRC_RegionOffsets_t	*item6_49	/* OPTIONAL */;
	DSRC_RegionPointSet_t	*item6_50	/* OPTIONAL */;
	DSRC_RoadSignID_t	*item6_51	/* OPTIONAL */;
	DSRC_RTCMHeader_t	*item6_52	/* OPTIONAL */;
	DSRC_RTCMmsg_t	*item6_53	/* OPTIONAL */;
	DSRC_RTCMPackage_t	*item6_54	/* OPTIONAL */;
	DSRC_Sample_t	*item6_55	/* OPTIONAL */;
	DSRC_ShapePointSet_t	*item6_56	/* OPTIONAL */;
	DSRC_SignalControlZone_t	*item6_57	/* OPTIONAL */;
	DSRC_SignalRequest_t	*item6_58	/* OPTIONAL */;
	DSRC_SnapshotDistance_t	*item6_59	/* OPTIONAL */;
	DSRC_Snapshot_t	*item6_60	/* OPTIONAL */;
	DSRC_SnapshotTime_t	*item6_61	/* OPTIONAL */;
	DSRC_SpecialLane_t	*item6_62	/* OPTIONAL */;
	DSRC_SpeedandHeadingandThrottleConfidence_t	*item6_63	/* OPTIONAL */;
	DSRC_TransmissionAndSpeed_t	*item6_64	/* OPTIONAL */;
	DSRC_ValidRegion_t	*item6_65	/* OPTIONAL */;
	DSRC_VehicleComputedLane_t	*item6_66	/* OPTIONAL */;
	DSRC_VehicleIdent_t	*item6_67	/* OPTIONAL */;
	DSRC_VehicleReferenceLane_t	*item6_68	/* OPTIONAL */;
	DSRC_VehicleSafetyExtension_t	*item6_69	/* OPTIONAL */;
	DSRC_VehicleSize_t	*item6_70	/* OPTIONAL */;
	DSRC_VehicleStatusRequest_t	*item6_71	/* OPTIONAL */;
	DSRC_VehicleStatus_t	*item6_72	/* OPTIONAL */;
	DSRC_WiperStatus_t	*item6_73	/* OPTIONAL */;
	DSRC_Acceleration_t	*item7_1	/* OPTIONAL */;
	DSRC_AccelerationConfidence_t	*item7_2	/* OPTIONAL */;
	DSRC_AmbientAirPressure_t	*item7_3	/* OPTIONAL */;
	DSRC_AmbientAirTemperature_t	*item7_4	/* OPTIONAL */;
	DSRC_AntiLockBrakeStatus_t	*item7_5	/* OPTIONAL */;
	DSRC_ApproachNumber_t	*item7_6	/* OPTIONAL */;
	DSRC_AuxiliaryBrakeStatus_t	*item7_7	/* OPTIONAL */;
	DSRC_BarrierAttributes_t	*item7_8	/* OPTIONAL */;
	DSRC_BrakeAppliedPressure_t	*item7_9	/* OPTIONAL */;
	DSRC_BrakeAppliedStatus_t	*item7_10	/* OPTIONAL */;
	DSRC_BrakeBoostApplied_t	*item7_11	/* OPTIONAL */;
	DSRC_BumperHeightFront_t	*item7_12	/* OPTIONAL */;
	DSRC_BumperHeightRear_t	*item7_13	/* OPTIONAL */;
	DSRC_CodeWord_t	*item7_14	/* OPTIONAL */;
	DSRC_CoefficientOfFriction_t	*item7_15	/* OPTIONAL */;
	DSRC_ColorState_t	*item7_16	/* OPTIONAL */;
	DSRC_Count_t	*item7_17	/* OPTIONAL */;
	DSRC_CrosswalkLaneAttributes_t	*item7_18	/* OPTIONAL */;
	DSRC_DDay_t	*item7_19	/* OPTIONAL */;
	DSRC_DescriptiveName_t	*item7_20	/* OPTIONAL */;
	DSRC_DHour_t	*item7_21	/* OPTIONAL */;
	DSRC_DirectionOfUse_t	*item7_22	/* OPTIONAL */;
	DSRC_DMinute_t	*item7_23	/* OPTIONAL */;
	DSRC_DMonth_t	*item7_24	/* OPTIONAL */;
	DSRC_DOffset_t	*item7_25	/* OPTIONAL */;
	DSRC_DrivenLineOffset_t	*item7_26	/* OPTIONAL */;
	DSRC_DrivingWheelAngle_t	*item7_27	/* OPTIONAL */;
	DSRC_DSecond_t	*item7_28	/* OPTIONAL */;
	DSRC_DSignalSeconds_t	*item7_29	/* OPTIONAL */;
	DSRC_DSRCmsgID_t	*item7_30	/* OPTIONAL */;
	DSRC_DYear_t	*item7_31	/* OPTIONAL */;
	DSRC_ElevationConfidence_t	*item7_32	/* OPTIONAL */;
	DSRC_Elevation_t	*item7_33	/* OPTIONAL */;
	DSRC_EmergencyDetails_t	*item7_34	/* OPTIONAL */;
	DSRC_EventFlags_t	*item7_35	/* OPTIONAL */;
	DSRC_Extent_t	*item7_36	/* OPTIONAL */;
	DSRC_ExteriorLights_t	*item7_37	/* OPTIONAL */;
	DSRC_FurtherInfoID_t	*item7_38	/* OPTIONAL */;
	DSRC_GPSstatus_t	*item7_39	/* OPTIONAL */;
	DSRC_HeadingConfidence_t	*item7_40	/* OPTIONAL */;
	DSRC_Heading_t	*item7_41	/* OPTIONAL */;
	DSRC_HeadingSlice_t	*item7_42	/* OPTIONAL */;
	DSRC_IntersectionStatusObject_t	*item7_43	/* OPTIONAL */;
	DSRC_IntersectionID_t	*item7_44	/* OPTIONAL */;
	DSRC_AxleLocation_t	*item7_45	/* OPTIONAL */;
	DSRC_AxleWeight_t	*item7_46	/* OPTIONAL */;
	DSRC_CargoWeight_t	*item7_47	/* OPTIONAL */;
	DSRC_DriveAxleLiftAirPressure_t	*item7_48	/* OPTIONAL */;
	DSRC_DriveAxleLocation_t	*item7_49	/* OPTIONAL */;
	DSRC_DriveAxleLubePressure_t	*item7_50	/* OPTIONAL */;
	DSRC_DriveAxleTemperature_t	*item7_51	/* OPTIONAL */;
	DSRC_SteeringAxleLubePressure_t	*item7_52	/* OPTIONAL */;
	DSRC_SteeringAxleTemperature_t	*item7_53	/* OPTIONAL */;
	DSRC_TireLeakageRate_t	*item7_54	/* OPTIONAL */;
	DSRC_TireLocation_t	*item7_55	/* OPTIONAL */;
	DSRC_TirePressureThresholdDetection_t	*item7_56	/* OPTIONAL */;
	DSRC_TirePressure_t	*item7_57	/* OPTIONAL */;
	DSRC_TireTemp_t	*item7_58	/* OPTIONAL */;
	DSRC_TrailerWeight_t	*item7_59	/* OPTIONAL */;
	DSRC_WheelEndElectFault_t	*item7_60	/* OPTIONAL */;
	DSRC_WheelSensorStatus_t	*item7_61	/* OPTIONAL */;
	DSRC_LaneCount_t	*item7_62	/* OPTIONAL */;
	DSRC_LaneManeuverCode_t	*item7_63	/* OPTIONAL */;
	DSRC_LaneNumber_t	*item7_64	/* OPTIONAL */;
	DSRC_LaneSet_t	*item7_65	/* OPTIONAL */;
	DSRC_LaneWidth_t	*item7_66	/* OPTIONAL */;
	DSRC_Latitude_t	*item7_67	/* OPTIONAL */;
	DSRC_LayerID_t	*item7_68	/* OPTIONAL */;
	DSRC_LayerType_t	*item7_69	/* OPTIONAL */;
	DSRC_LightbarInUse_t	*item7_70	/* OPTIONAL */;
	DSRC_Longitude_t	*item7_71	/* OPTIONAL */;
	DSRC_Location_quality_t	*item7_72	/* OPTIONAL */;
	DSRC_Location_tech_t	*item7_73	/* OPTIONAL */;
	DSRC_MinuteOfTheYear_t	*item7_74	/* OPTIONAL */;
	DSRC_MinutesDuration_t	*item7_75	/* OPTIONAL */;
	DSRC_MsgCount_t	*item7_76	/* OPTIONAL */;
	DSRC_MsgCRC_t	*item7_77	/* OPTIONAL */;
	DSRC_MultiVehicleResponse_t	*item7_78	/* OPTIONAL */;
	DSRC_MUTCDCode_t	*item7_79	/* OPTIONAL */;
	DSRC_NMEA_MsgType_t	*item7_80	/* OPTIONAL */;
	DSRC_NMEA_Payload_t	*item7_81	/* OPTIONAL */;
	DSRC_NMEA_Revision_t	*item7_82	/* OPTIONAL */;
	DSRC_NTCIPVehicleclass_t	*item7_83	/* OPTIONAL */;
	DSRC_ObjectCount_t	*item7_84	/* OPTIONAL */;
	DSRC_ObstacleDirection_t	*item7_85	/* OPTIONAL */;
	DSRC_ObstacleDistance_t	*item7_86	/* OPTIONAL */;
	DSRC_PayloadData_t	*item7_87	/* OPTIONAL */;
	DSRC_Payload_t	*item7_88	/* OPTIONAL */;
	DSRC_PedestrianDetect_t	*item7_89	/* OPTIONAL */;
	DSRC_PedestrianSignalState_t	*item7_90	/* OPTIONAL */;
	DSRC_PositionConfidence_t	*item7_91	/* OPTIONAL */;
	DSRC_PreemptState_t	*item7_92	/* OPTIONAL */;
	DSRC_Priority_t	*item7_93	/* OPTIONAL */;
	DSRC_PriorityState_t	*item7_94	/* OPTIONAL */;
	DSRC_ProbeSegmentNumber_t	*item7_95	/* OPTIONAL */;
	DSRC_RainSensor_t	*item7_96	/* OPTIONAL */;
	DSRC_RequestedItem_t	*item7_97	/* OPTIONAL */;
	DSRC_ResponseType_t	*item7_98	/* OPTIONAL */;
	DSRC_RTCM_ID_t	*item7_99	/* OPTIONAL */;
	DSRC_RTCM_Payload_t	*item7_100	/* OPTIONAL */;
	DSRC_RTCM_Revision_t	*item7_101	/* OPTIONAL */;
	DSRC_SignalLightState_t	*item7_102	/* OPTIONAL */;
	DSRC_SignalReqScheme_t	*item7_103	/* OPTIONAL */;
	DSRC_SignalState_t	*item7_104	/* OPTIONAL */;
	DSRC_SignPrority_t	*item7_105	/* OPTIONAL */;
	DSRC_SirenInUse_t	*item7_106	/* OPTIONAL */;
	DSRC_SpecialLaneAttributes_t	*item7_107	/* OPTIONAL */;
	DSRC_SpecialSignalState_t	*item7_108	/* OPTIONAL */;
	DSRC_SpeedConfidence_t	*item7_109	/* OPTIONAL */;
	DSRC_Speed_t	*item7_110	/* OPTIONAL */;
	DSRC_StabilityControlStatus_t	*item7_111	/* OPTIONAL */;
	DSRC_StateConfidence_t	*item7_112	/* OPTIONAL */;
	DSRC_SteeringWheelAngleConfidence_t	*item7_113	/* OPTIONAL */;
	DSRC_SteeringWheelAngleRateOfChange_t	*item7_114	/* OPTIONAL */;
	DSRC_SteeringWheelAngle_t	*item7_115	/* OPTIONAL */;
	DSRC_SunSensor_t	*item7_116	/* OPTIONAL */;
	DSRC_TemporaryID_t	*item7_117	/* OPTIONAL */;
	DSRC_TermDistance_t	*item7_118	/* OPTIONAL */;
	DSRC_TermTime_t	*item7_119	/* OPTIONAL */;
	DSRC_ThrottleConfidence_t	*item7_120	/* OPTIONAL */;
	DSRC_ThrottlePosition_t	*item7_121	/* OPTIONAL */;
	DSRC_TimeConfidence_t	*item7_122	/* OPTIONAL */;
	DSRC_TimeMark_t	*item7_123	/* OPTIONAL */;
	DSRC_TractionControlState_t	*item7_124	/* OPTIONAL */;
	DSRC_TransitPreEmptionRequest_t	*item7_125	/* OPTIONAL */;
	DSRC_TransitStatus_t	*item7_126	/* OPTIONAL */;
	DSRC_TransmissionState_t	*item7_127	/* OPTIONAL */;
	DSRC_TxTime_t	*item7_128	/* OPTIONAL */;
	DSRC_TravelerInfoType_t	*item7_129	/* OPTIONAL */;
	DSRC_UniqueMSGID_t	*item7_130	/* OPTIONAL */;
	DSRC_URL_Base_t	*item7_131	/* OPTIONAL */;
	DSRC_URL_Link_t	*item7_132	/* OPTIONAL */;
	DSRC_URL_Short_t	*item7_133	/* OPTIONAL */;
	DSRC_VehicleHeight_t	*item7_134	/* OPTIONAL */;
	DSRC_VehicleLaneAttributes_t	*item7_135	/* OPTIONAL */;
	DSRC_VehicleLength_t	*item7_136	/* OPTIONAL */;
	DSRC_VehicleMass_t	*item7_137	/* OPTIONAL */;
	DSRC_VehicleRequestStatus_t	*item7_138	/* OPTIONAL */;
	DSRC_VehicleStatusDeviceTypeTag_t	*item7_139	/* OPTIONAL */;
	DSRC_VehicleType_t	*item7_140	/* OPTIONAL */;
	DSRC_VehicleWidth_t	*item7_141	/* OPTIONAL */;
	DSRC_VerticalAccelerationThreshold_t	*item7_142	/* OPTIONAL */;
	DSRC_VerticalAcceleration_t	*item7_143	/* OPTIONAL */;
	DSRC_VINstring_t	*item7_144	/* OPTIONAL */;
	DSRC_WiperRate_t	*item7_145	/* OPTIONAL */;
	DSRC_WiperStatusFront_t	*item7_146	/* OPTIONAL */;
	DSRC_WiperStatusRear_t	*item7_147	/* OPTIONAL */;
	DSRC_YawRateConfidence_t	*item7_148	/* OPTIONAL */;
	DSRC_YawRate_t	*item7_149	/* OPTIONAL */;
	DSRC_IncidentResponseEquipment_t	*item8_1	/* OPTIONAL */;
	DSRC_ITIStext_t	*item8_2	/* OPTIONAL */;
	DSRC_ResponderGroupAffected_t	*item8_3	/* OPTIONAL */;
	DSRC_VehicleGroupAffected_t	*item8_4	/* OPTIONAL */;
	DSRC_ITIScodesAndText_t	*item8_5	/* OPTIONAL */;
	DSRC_EssMobileFriction_t	*item8_6	/* OPTIONAL */;
	DSRC_EssPrecipRate_t	*item8_7	/* OPTIONAL */;
	DSRC_EssPrecipSituation_t	*item8_8	/* OPTIONAL */;
	DSRC_EssPrecipYesNo_t	*item8_9	/* OPTIONAL */;
	DSRC_EssSolarRadiation_t	*item8_10	/* OPTIONAL */;
	DSRC_ITIScodes_t	*item8_11	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_AllInclusive_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_AllInclusive;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_AllInclusive_H_ */
#include <asn_internal.h>
