/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_SignalControlZone_H_
#define	_DSRC_SignalControlZone_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DescriptiveName.h"
#include "DSRC_SignalReqScheme.h"
#include "DSRC_LaneNumber.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "DSRC_LaneWidth.h"
#include "DSRC_NodeList.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_SignalControlZone__data_PR {
	DSRC_SignalControlZone__data_PR_NOTHING,	/* No components present */
	DSRC_SignalControlZone__data_PR_laneSet,
	DSRC_SignalControlZone__data_PR_zones
} DSRC_SignalControlZone__data_PR;

/* DSRC_SignalControlZone */
typedef struct DSRC_SignalControlZone {
	DSRC_DescriptiveName_t	*name	/* OPTIONAL */;
	DSRC_SignalReqScheme_t	 pValue;
	struct DSRC_SignalControlZone__data {
		DSRC_SignalControlZone__data_PR present;
		union DSRC_SignalControlZone__data_u {
			struct DSRC_SignalControlZone__data__laneSet {
				A_SEQUENCE_OF(DSRC_LaneNumber_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} laneSet;
			struct DSRC_SignalControlZone__data__zones {
				A_SEQUENCE_OF(struct DSRC_SignalControlZone__data__zones__Member {
					struct enclosed {
						A_SEQUENCE_OF(DSRC_LaneNumber_t) list;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *enclosed;
					DSRC_LaneWidth_t	*laneWidth	/* OPTIONAL */;
					DSRC_NodeList_t	 nodeList;
					/*
					 * This type is extensible,
					 * possible extensions are below.
					 */
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} zones;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} data;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_SignalControlZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_SignalControlZone;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_SignalControlZone_H_ */
#include <asn_internal.h>
