/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_RoadSideAlert_H_
#define	_DSRC_RoadSideAlert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_MsgCount.h"
#include "DSRC_ITIScodes.h"
#include "DSRC_Priority.h"
#include "DSRC_HeadingSlice.h"
#include "DSRC_Extent.h"
#include "DSRC_FullPositionVector.h"
#include "DSRC_FurtherInfoID.h"
#include "DSRC_MsgCRC.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_RoadSideAlert */
typedef struct DSRC_RoadSideAlert {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_MsgCount_t	 msgCnt;
	DSRC_ITIScodes_t	 typeEvent;
	struct DSRC_RoadSideAlert__description {
		A_SEQUENCE_OF(DSRC_ITIScodes_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *description;
	DSRC_Priority_t	*priority	/* OPTIONAL */;
	DSRC_HeadingSlice_t	*heading	/* OPTIONAL */;
	DSRC_Extent_t	*extent	/* OPTIONAL */;
	DSRC_FullPositionVector_t	*positon	/* OPTIONAL */;
	DSRC_FurtherInfoID_t	*furtherInfoID	/* OPTIONAL */;
	DSRC_MsgCRC_t	 crc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_RoadSideAlert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_RoadSideAlert;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_RoadSideAlert_H_ */
#include <asn_internal.h>
