/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#include "DSRC_NMEA-Corrections.h"

static int
memb_wdCount_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0l && value <= 1023l)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_DSRC_NMEA_Corrections_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DSRC_NMEA_Corrections, msgID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_DSRCmsgID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msgID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DSRC_NMEA_Corrections, rev),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_NMEA_Revision,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rev"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DSRC_NMEA_Corrections, msg),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_NMEA_MsgType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DSRC_NMEA_Corrections, wdCount),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_wdCount_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"wdCount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DSRC_NMEA_Corrections, payload),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRC_NMEA_Payload,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"payload"
		},
};
static const ber_tlv_tag_t asn_DEF_DSRC_NMEA_Corrections_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DSRC_NMEA_Corrections_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rev */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* msg */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* wdCount */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* payload */
};
static asn_SEQUENCE_specifics_t asn_SPC_DSRC_NMEA_Corrections_specs_1 = {
	sizeof(struct DSRC_NMEA_Corrections),
	offsetof(struct DSRC_NMEA_Corrections, _asn_ctx),
	asn_MAP_DSRC_NMEA_Corrections_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DSRC_NMEA_Corrections = {
	"DSRC_NMEA-Corrections",
	"DSRC_NMEA-Corrections",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No UPER support, use "-gen-PER" to enable */
	0, 0,	/* No APER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DSRC_NMEA_Corrections_tags_1,
	sizeof(asn_DEF_DSRC_NMEA_Corrections_tags_1)
		/sizeof(asn_DEF_DSRC_NMEA_Corrections_tags_1[0]), /* 1 */
	asn_DEF_DSRC_NMEA_Corrections_tags_1,	/* Same as above */
	sizeof(asn_DEF_DSRC_NMEA_Corrections_tags_1)
		/sizeof(asn_DEF_DSRC_NMEA_Corrections_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DSRC_NMEA_Corrections_1,
	5,	/* Elements count */
	&asn_SPC_DSRC_NMEA_Corrections_specs_1	/* Additional specs */
};

