/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_VehicleDataV2VI_H_
#define	_DSRC_VehicleDataV2VI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_VehicleHeight.h"
#include "DSRC_BumperHeights.h"
#include "DSRC_VehicleMass.h"
#include "DSRC_TrailerWeight.h"
#include "DSRC_VehicleType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_VehicleDataV2VI */
typedef struct DSRC_VehicleDataV2VI {
	DSRC_VehicleHeight_t	*height	/* OPTIONAL */;
	DSRC_BumperHeights_t	*bumpers	/* OPTIONAL */;
	DSRC_VehicleMass_t	*mass	/* OPTIONAL */;
	DSRC_TrailerWeight_t	*trailerWeight	/* OPTIONAL */;
	DSRC_VehicleType_t	*type	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_VehicleDataV2VI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_VehicleDataV2VI;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_VehicleDataV2VI_H_ */
#include <asn_internal.h>
