/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_Approach_H_
#define	_DSRC_Approach_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DescriptiveName.h"
#include "DSRC_ApproachNumber.h"
#include "DSRC_VehicleReferenceLane.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "DSRC_VehicleComputedLane.h"
#include "DSRC_SpecialLane.h"
#include "DSRC_BarrierLane.h"
#include "DSRC_CrosswalkLane.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_Approach */
typedef struct DSRC_Approach {
	DSRC_DescriptiveName_t	*name	/* OPTIONAL */;
	DSRC_ApproachNumber_t	*id	/* OPTIONAL */;
	struct DSRC_Approach__drivingLanes {
		A_SEQUENCE_OF(DSRC_VehicleReferenceLane_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *drivingLanes;
	struct DSRC_Approach__computedLanes {
		A_SEQUENCE_OF(DSRC_VehicleComputedLane_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *computedLanes;
	struct DSRC_Approach__trainsAndBuses {
		A_SEQUENCE_OF(DSRC_SpecialLane_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *trainsAndBuses;
	struct DSRC_Approach__barriers {
		A_SEQUENCE_OF(DSRC_BarrierLane_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *barriers;
	struct DSRC_Approach__crosswalks {
		A_SEQUENCE_OF(DSRC_CrosswalkLane_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *crosswalks;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_Approach_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_Approach;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_Approach_H_ */
#include <asn_internal.h>
