/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_SpecialSignalState_H_
#define	_DSRC_SpecialSignalState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_SpecialSignalState {
	DSRC_SpecialSignalState_unknown	= 0,
	DSRC_SpecialSignalState_notInUse	= 1,
	DSRC_SpecialSignalState_arriving	= 2,
	DSRC_SpecialSignalState_present	= 3,
	DSRC_SpecialSignalState_departing	= 4
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_SpecialSignalState;

/* DSRC_SpecialSignalState */
typedef long	 DSRC_SpecialSignalState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_SpecialSignalState;
asn_struct_free_f DSRC_SpecialSignalState_free;
asn_struct_print_f DSRC_SpecialSignalState_print;
asn_constr_check_f DSRC_SpecialSignalState_constraint;
ber_type_decoder_f DSRC_SpecialSignalState_decode_ber;
der_type_encoder_f DSRC_SpecialSignalState_encode_der;
xer_type_decoder_f DSRC_SpecialSignalState_decode_xer;
xer_type_encoder_f DSRC_SpecialSignalState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_SpecialSignalState_H_ */
#include <asn_internal.h>
