/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_ColorState_H_
#define	_DSRC_ColorState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_ColorState {
	DSRC_ColorState_dark	= 0,
	DSRC_ColorState_green	= 1,
	DSRC_ColorState_green_flashing	= 9,
	DSRC_ColorState_yellow	= 2,
	DSRC_ColorState_yellow_flashing	= 10,
	DSRC_ColorState_red	= 4,
	DSRC_ColorState_red_flashing	= 12
} e_DSRC_ColorState;

/* DSRC_ColorState */
typedef long	 DSRC_ColorState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_ColorState;
asn_struct_free_f DSRC_ColorState_free;
asn_struct_print_f DSRC_ColorState_print;
asn_constr_check_f DSRC_ColorState_constraint;
ber_type_decoder_f DSRC_ColorState_decode_ber;
der_type_encoder_f DSRC_ColorState_encode_der;
xer_type_decoder_f DSRC_ColorState_decode_xer;
xer_type_encoder_f DSRC_ColorState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_ColorState_H_ */
#include <asn_internal.h>
