/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_ThrottleConfidence_H_
#define	_DSRC_ThrottleConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_ThrottleConfidence {
	DSRC_ThrottleConfidence_unavailable	= 0,
	DSRC_ThrottleConfidence_prec10percent	= 1,
	DSRC_ThrottleConfidence_prec1percent	= 2,
	DSRC_ThrottleConfidence_prec0_5percent	= 3
} e_DSRC_ThrottleConfidence;

/* DSRC_ThrottleConfidence */
typedef long	 DSRC_ThrottleConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_ThrottleConfidence;
asn_struct_free_f DSRC_ThrottleConfidence_free;
asn_struct_print_f DSRC_ThrottleConfidence_print;
asn_constr_check_f DSRC_ThrottleConfidence_constraint;
ber_type_decoder_f DSRC_ThrottleConfidence_decode_ber;
der_type_encoder_f DSRC_ThrottleConfidence_encode_der;
xer_type_decoder_f DSRC_ThrottleConfidence_decode_xer;
xer_type_encoder_f DSRC_ThrottleConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_ThrottleConfidence_H_ */
#include <asn_internal.h>
