/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_FullPositionVector_H_
#define	_DSRC_FullPositionVector_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DDateTime.h"
#include "DSRC_Longitude.h"
#include "DSRC_Latitude.h"
#include "DSRC_Elevation.h"
#include "DSRC_Heading.h"
#include "DSRC_TransmissionAndSpeed.h"
#include "DSRC_PositionalAccuracy.h"
#include "DSRC_TimeConfidence.h"
#include "DSRC_PositionConfidenceSet.h"
#include "DSRC_SpeedandHeadingandThrottleConfidence.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_FullPositionVector */
typedef struct DSRC_FullPositionVector {
	DSRC_DDateTime_t	*utcTime	/* OPTIONAL */;
	DSRC_Longitude_t	 Long;
	DSRC_Latitude_t	 lat;
	DSRC_Elevation_t	*elevation	/* OPTIONAL */;
	DSRC_Heading_t	*heading	/* OPTIONAL */;
	DSRC_TransmissionAndSpeed_t	*speed	/* OPTIONAL */;
	DSRC_PositionalAccuracy_t	*posAccuracy	/* OPTIONAL */;
	DSRC_TimeConfidence_t	*timeConfidence	/* OPTIONAL */;
	DSRC_PositionConfidenceSet_t	*posConfidence	/* OPTIONAL */;
	DSRC_SpeedandHeadingandThrottleConfidence_t	*speedConfidence	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_FullPositionVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_FullPositionVector;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_FullPositionVector_H_ */
#include <asn_internal.h>
