/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NTCIP"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_EssPrecipYesNo_H_
#define	_DSRC_EssPrecipYesNo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_EssPrecipYesNo {
	DSRC_EssPrecipYesNo_precip	= 1,
	DSRC_EssPrecipYesNo_noPrecip	= 2,
	DSRC_EssPrecipYesNo_error	= 3
} e_DSRC_EssPrecipYesNo;

/* DSRC_EssPrecipYesNo */
typedef long	 DSRC_EssPrecipYesNo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_EssPrecipYesNo;
asn_struct_free_f DSRC_EssPrecipYesNo_free;
asn_struct_print_f DSRC_EssPrecipYesNo_print;
asn_constr_check_f DSRC_EssPrecipYesNo_constraint;
ber_type_decoder_f DSRC_EssPrecipYesNo_decode_ber;
der_type_encoder_f DSRC_EssPrecipYesNo_encode_der;
xer_type_decoder_f DSRC_EssPrecipYesNo_decode_xer;
xer_type_encoder_f DSRC_EssPrecipYesNo_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_EssPrecipYesNo_H_ */
#include <asn_internal.h>
