/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_RTCM_Revision_H_
#define	_DSRC_RTCM_Revision_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_RTCM_Revision {
	DSRC_RTCM_Revision_unknown	= 0,
	DSRC_RTCM_Revision_reserved	= 1,
	DSRC_RTCM_Revision_rtcmCMR	= 2,
	DSRC_RTCM_Revision_rtcmCMR_Plus	= 3,
	DSRC_RTCM_Revision_rtcmSAPOS	= 4,
	DSRC_RTCM_Revision_rtcmSAPOS_Adv	= 5,
	DSRC_RTCM_Revision_rtcmRTCA	= 6,
	DSRC_RTCM_Revision_rtcmRAW	= 7,
	DSRC_RTCM_Revision_rtcmRINEX	= 8,
	DSRC_RTCM_Revision_rtcmSP3	= 9,
	DSRC_RTCM_Revision_rtcmBINEX	= 10,
	DSRC_RTCM_Revision_rtcmRev2_x	= 19,
	DSRC_RTCM_Revision_rtcmRev2_0	= 20,
	DSRC_RTCM_Revision_rtcmRev2_1	= 21,
	DSRC_RTCM_Revision_rtcmRev2_3	= 23,
	DSRC_RTCM_Revision_rtcmRev3_0	= 30,
	DSRC_RTCM_Revision_rtcmRev3_1	= 31
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_RTCM_Revision;

/* DSRC_RTCM-Revision */
typedef long	 DSRC_RTCM_Revision_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_RTCM_Revision;
asn_struct_free_f DSRC_RTCM_Revision_free;
asn_struct_print_f DSRC_RTCM_Revision_print;
asn_constr_check_f DSRC_RTCM_Revision_constraint;
ber_type_decoder_f DSRC_RTCM_Revision_decode_ber;
der_type_encoder_f DSRC_RTCM_Revision_encode_der;
xer_type_decoder_f DSRC_RTCM_Revision_decode_xer;
xer_type_encoder_f DSRC_RTCM_Revision_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_RTCM_Revision_H_ */
#include <asn_internal.h>
