/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_StateConfidence_H_
#define	_DSRC_StateConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_StateConfidence {
	DSRC_StateConfidence_unKnownEstimate	= 0,
	DSRC_StateConfidence_minTime	= 1,
	DSRC_StateConfidence_maxTime	= 2,
	DSRC_StateConfidence_timeLikeklyToChange	= 3
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_StateConfidence;

/* DSRC_StateConfidence */
typedef long	 DSRC_StateConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_StateConfidence;
asn_struct_free_f DSRC_StateConfidence_free;
asn_struct_print_f DSRC_StateConfidence_print;
asn_constr_check_f DSRC_StateConfidence_constraint;
ber_type_decoder_f DSRC_StateConfidence_decode_ber;
der_type_encoder_f DSRC_StateConfidence_encode_der;
xer_type_decoder_f DSRC_StateConfidence_decode_xer;
xer_type_encoder_f DSRC_StateConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_StateConfidence_H_ */
#include <asn_internal.h>
