/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_IntersectionState_H_
#define	_DSRC_IntersectionState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DescriptiveName.h"
#include "DSRC_IntersectionID.h"
#include "DSRC_IntersectionStatusObject.h"
#include "DSRC_TimeMark.h"
#include <NativeInteger.h>
#include "DSRC_SignalState.h"
#include "DSRC_MovementState.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_IntersectionState */
typedef struct DSRC_IntersectionState {
	DSRC_DescriptiveName_t	*name	/* OPTIONAL */;
	DSRC_IntersectionID_t	 id;
	DSRC_IntersectionStatusObject_t	 status;
	DSRC_TimeMark_t	*timeStamp	/* OPTIONAL */;
	long	*lanesCnt	/* OPTIONAL */;
	struct DSRC_IntersectionState__states {
		A_SEQUENCE_OF(DSRC_MovementState_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} states;
	DSRC_SignalState_t	*priority	/* OPTIONAL */;
	DSRC_SignalState_t	*preempt	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_IntersectionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_IntersectionState;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_IntersectionState_H_ */
#include <asn_internal.h>
