/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_CrosswalkLane_H_
#define	_DSRC_CrosswalkLane_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_LaneNumber.h"
#include "DSRC_LaneWidth.h"
#include "DSRC_CrosswalkLaneAttributes.h"
#include "DSRC_NodeList.h"
#include "DSRC_ConnectsTo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_CrosswalkLane */
typedef struct DSRC_CrosswalkLane {
	DSRC_LaneNumber_t	 laneNumber;
	DSRC_LaneWidth_t	*laneWidth	/* OPTIONAL */;
	DSRC_CrosswalkLaneAttributes_t	 laneAttributes;
	DSRC_NodeList_t	 nodeList;
	DSRC_NodeList_t	*keepOutList	/* OPTIONAL */;
	DSRC_ConnectsTo_t	*connectsTo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_CrosswalkLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_CrosswalkLane;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_CrosswalkLane_H_ */
#include <asn_internal.h>
