/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_Circle_H_
#define	_DSRC_Circle_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_Position3D.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_Circle__raduis_PR {
	DSRC_Circle__raduis_PR_NOTHING,	/* No components present */
	DSRC_Circle__raduis_PR_radiusSteps,
	DSRC_Circle__raduis_PR_miles,
	DSRC_Circle__raduis_PR_km
} DSRC_Circle__raduis_PR;

/* DSRC_Circle */
typedef struct DSRC_Circle {
	DSRC_Position3D_t	 center;
	struct DSRC_Circle__raduis {
		DSRC_Circle__raduis_PR present;
		union DSRC_Circle__raduis_u {
			long	 radiusSteps;
			long	 miles;
			long	 km;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} raduis;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_Circle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_Circle;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_Circle_H_ */
#include <asn_internal.h>
