/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_DrivingWheelAngle_H_
#define	_DSRC_DrivingWheelAngle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_DrivingWheelAngle */
typedef long	 DSRC_DrivingWheelAngle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_DrivingWheelAngle;
asn_struct_free_f DSRC_DrivingWheelAngle_free;
asn_struct_print_f DSRC_DrivingWheelAngle_print;
asn_constr_check_f DSRC_DrivingWheelAngle_constraint;
ber_type_decoder_f DSRC_DrivingWheelAngle_decode_ber;
der_type_encoder_f DSRC_DrivingWheelAngle_encode_der;
xer_type_decoder_f DSRC_DrivingWheelAngle_decode_xer;
xer_type_encoder_f DSRC_DrivingWheelAngle_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_DrivingWheelAngle_H_ */
#include <asn_internal.h>
