/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_ElevationConfidence_H_
#define	_DSRC_ElevationConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_ElevationConfidence {
	DSRC_ElevationConfidence_unavailable	= 0,
	DSRC_ElevationConfidence_elev_500_00	= 1,
	DSRC_ElevationConfidence_elev_200_00	= 2,
	DSRC_ElevationConfidence_elev_100_00	= 3,
	DSRC_ElevationConfidence_elev_050_00	= 4,
	DSRC_ElevationConfidence_elev_020_00	= 5,
	DSRC_ElevationConfidence_elev_010_00	= 6,
	DSRC_ElevationConfidence_elev_005_00	= 7,
	DSRC_ElevationConfidence_elev_002_00	= 8,
	DSRC_ElevationConfidence_elev_001_00	= 9,
	DSRC_ElevationConfidence_elev_000_50	= 10,
	DSRC_ElevationConfidence_elev_000_20	= 11,
	DSRC_ElevationConfidence_elev_000_10	= 12,
	DSRC_ElevationConfidence_elev_000_05	= 13,
	DSRC_ElevationConfidence_elev_000_02	= 14,
	DSRC_ElevationConfidence_elev_000_01	= 15
} e_DSRC_ElevationConfidence;

/* DSRC_ElevationConfidence */
typedef long	 DSRC_ElevationConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_ElevationConfidence;
asn_struct_free_f DSRC_ElevationConfidence_free;
asn_struct_print_f DSRC_ElevationConfidence_print;
asn_constr_check_f DSRC_ElevationConfidence_constraint;
ber_type_decoder_f DSRC_ElevationConfidence_decode_ber;
der_type_encoder_f DSRC_ElevationConfidence_encode_der;
xer_type_decoder_f DSRC_ElevationConfidence_decode_xer;
xer_type_encoder_f DSRC_ElevationConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_ElevationConfidence_H_ */
#include <asn_internal.h>
