/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NTCIP"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_EssPrecipSituation_H_
#define	_DSRC_EssPrecipSituation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_EssPrecipSituation {
	DSRC_EssPrecipSituation_other	= 1,
	DSRC_EssPrecipSituation_unknown	= 2,
	DSRC_EssPrecipSituation_noPrecipitation	= 3,
	DSRC_EssPrecipSituation_unidentifiedSlight	= 4,
	DSRC_EssPrecipSituation_unidentifiedModerate	= 5,
	DSRC_EssPrecipSituation_unidentifiedHeavy	= 6,
	DSRC_EssPrecipSituation_snowSlight	= 7,
	DSRC_EssPrecipSituation_snowModerate	= 8,
	DSRC_EssPrecipSituation_snowHeavy	= 9,
	DSRC_EssPrecipSituation_rainSlight	= 10,
	DSRC_EssPrecipSituation_rainModerate	= 11,
	DSRC_EssPrecipSituation_rainHeavy	= 12,
	DSRC_EssPrecipSituation_frozenPrecipitationSlight	= 13,
	DSRC_EssPrecipSituation_frozenPrecipitationModerate	= 14,
	DSRC_EssPrecipSituation_frozenPrecipitationHeavy	= 15
} e_DSRC_EssPrecipSituation;

/* DSRC_EssPrecipSituation */
typedef long	 DSRC_EssPrecipSituation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_EssPrecipSituation;
asn_struct_free_f DSRC_EssPrecipSituation_free;
asn_struct_print_f DSRC_EssPrecipSituation_print;
asn_constr_check_f DSRC_EssPrecipSituation_constraint;
ber_type_decoder_f DSRC_EssPrecipSituation_decode_ber;
der_type_encoder_f DSRC_EssPrecipSituation_encode_der;
xer_type_decoder_f DSRC_EssPrecipSituation_decode_xer;
xer_type_encoder_f DSRC_EssPrecipSituation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_EssPrecipSituation_H_ */
#include <asn_internal.h>
