/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_VehicleStatusDeviceTypeTag_H_
#define	_DSRC_VehicleStatusDeviceTypeTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_VehicleStatusDeviceTypeTag {
	DSRC_VehicleStatusDeviceTypeTag_unknown	= 0,
	DSRC_VehicleStatusDeviceTypeTag_lights	= 1,
	DSRC_VehicleStatusDeviceTypeTag_wipers	= 2,
	DSRC_VehicleStatusDeviceTypeTag_brakes	= 3,
	DSRC_VehicleStatusDeviceTypeTag_stab	= 4,
	DSRC_VehicleStatusDeviceTypeTag_trac	= 5,
	DSRC_VehicleStatusDeviceTypeTag_abs	= 6,
	DSRC_VehicleStatusDeviceTypeTag_sunS	= 7,
	DSRC_VehicleStatusDeviceTypeTag_rainS	= 8,
	DSRC_VehicleStatusDeviceTypeTag_airTemp	= 9,
	DSRC_VehicleStatusDeviceTypeTag_steering	= 10,
	DSRC_VehicleStatusDeviceTypeTag_vertAccelThres	= 11,
	DSRC_VehicleStatusDeviceTypeTag_vertAccel	= 12,
	DSRC_VehicleStatusDeviceTypeTag_hozAccelLong	= 13,
	DSRC_VehicleStatusDeviceTypeTag_hozAccelLat	= 14,
	DSRC_VehicleStatusDeviceTypeTag_hozAccelCon	= 15,
	DSRC_VehicleStatusDeviceTypeTag_accel4way	= 16,
	DSRC_VehicleStatusDeviceTypeTag_confidenceSet	= 17,
	DSRC_VehicleStatusDeviceTypeTag_obDist	= 18,
	DSRC_VehicleStatusDeviceTypeTag_obDirect	= 19,
	DSRC_VehicleStatusDeviceTypeTag_yaw	= 20,
	DSRC_VehicleStatusDeviceTypeTag_yawRateCon	= 21,
	DSRC_VehicleStatusDeviceTypeTag_dateTime	= 22,
	DSRC_VehicleStatusDeviceTypeTag_fullPos	= 23,
	DSRC_VehicleStatusDeviceTypeTag_position2D	= 24,
	DSRC_VehicleStatusDeviceTypeTag_position3D	= 25,
	DSRC_VehicleStatusDeviceTypeTag_vehicle	= 26,
	DSRC_VehicleStatusDeviceTypeTag_speedHeadC	= 27,
	DSRC_VehicleStatusDeviceTypeTag_speedC	= 28
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_VehicleStatusDeviceTypeTag;

/* DSRC_VehicleStatusDeviceTypeTag */
typedef long	 DSRC_VehicleStatusDeviceTypeTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_VehicleStatusDeviceTypeTag;
asn_struct_free_f DSRC_VehicleStatusDeviceTypeTag_free;
asn_struct_print_f DSRC_VehicleStatusDeviceTypeTag_print;
asn_constr_check_f DSRC_VehicleStatusDeviceTypeTag_constraint;
ber_type_decoder_f DSRC_VehicleStatusDeviceTypeTag_decode_ber;
der_type_encoder_f DSRC_VehicleStatusDeviceTypeTag_encode_der;
xer_type_decoder_f DSRC_VehicleStatusDeviceTypeTag_decode_xer;
xer_type_encoder_f DSRC_VehicleStatusDeviceTypeTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_VehicleStatusDeviceTypeTag_H_ */
#include <asn_internal.h>
