/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_RequestedItem_H_
#define	_DSRC_RequestedItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_RequestedItem {
	DSRC_RequestedItem_reserved	= 0,
	DSRC_RequestedItem_itemA	= 1,
	DSRC_RequestedItem_itemB	= 2,
	DSRC_RequestedItem_itemC	= 3,
	DSRC_RequestedItem_itemD	= 4,
	DSRC_RequestedItem_itemE	= 5,
	DSRC_RequestedItem_itemF	= 6,
	DSRC_RequestedItem_itemG	= 7,
	DSRC_RequestedItem_itemH	= 8,
	DSRC_RequestedItem_itemI	= 9,
	DSRC_RequestedItem_itemJ	= 10,
	DSRC_RequestedItem_itemK	= 11,
	DSRC_RequestedItem_itemL	= 12,
	DSRC_RequestedItem_itemM	= 13,
	DSRC_RequestedItem_itemN	= 14,
	DSRC_RequestedItem_itemO	= 15,
	DSRC_RequestedItem_itemP	= 16,
	DSRC_RequestedItem_itemQ	= 17
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_RequestedItem;

/* DSRC_RequestedItem */
typedef long	 DSRC_RequestedItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_RequestedItem;
asn_struct_free_f DSRC_RequestedItem_free;
asn_struct_print_f DSRC_RequestedItem_print;
asn_constr_check_f DSRC_RequestedItem_constraint;
ber_type_decoder_f DSRC_RequestedItem_decode_ber;
der_type_encoder_f DSRC_RequestedItem_encode_der;
xer_type_decoder_f DSRC_RequestedItem_decode_xer;
xer_type_encoder_f DSRC_RequestedItem_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_RequestedItem_H_ */
#include <asn_internal.h>
