/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_PositionConfidence_H_
#define	_DSRC_PositionConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_PositionConfidence {
	DSRC_PositionConfidence_unavailable	= 0,
	DSRC_PositionConfidence_a500m	= 1,
	DSRC_PositionConfidence_a200m	= 2,
	DSRC_PositionConfidence_a100m	= 3,
	DSRC_PositionConfidence_a50m	= 4,
	DSRC_PositionConfidence_a20m	= 5,
	DSRC_PositionConfidence_a10m	= 6,
	DSRC_PositionConfidence_a5m	= 7,
	DSRC_PositionConfidence_a2m	= 8,
	DSRC_PositionConfidence_a1m	= 9,
	DSRC_PositionConfidence_a50cm	= 10,
	DSRC_PositionConfidence_a20cm	= 11,
	DSRC_PositionConfidence_a10cm	= 12,
	DSRC_PositionConfidence_a5cm	= 13,
	DSRC_PositionConfidence_a2cm	= 14,
	DSRC_PositionConfidence_a1cm	= 15
} e_DSRC_PositionConfidence;

/* DSRC_PositionConfidence */
typedef long	 DSRC_PositionConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_PositionConfidence;
asn_struct_free_f DSRC_PositionConfidence_free;
asn_struct_print_f DSRC_PositionConfidence_print;
asn_constr_check_f DSRC_PositionConfidence_constraint;
ber_type_decoder_f DSRC_PositionConfidence_decode_ber;
der_type_encoder_f DSRC_PositionConfidence_encode_der;
xer_type_decoder_f DSRC_PositionConfidence_decode_xer;
xer_type_encoder_f DSRC_PositionConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_PositionConfidence_H_ */
#include <asn_internal.h>
