/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_CrosswalkLaneAttributes_H_
#define	_DSRC_CrosswalkLaneAttributes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_CrosswalkLaneAttributes {
	DSRC_CrosswalkLaneAttributes_noData	= 0,
	DSRC_CrosswalkLaneAttributes_twoWayPath	= 1,
	DSRC_CrosswalkLaneAttributes_pedestrianCrosswalk	= 2,
	DSRC_CrosswalkLaneAttributes_bikeLane	= 4,
	DSRC_CrosswalkLaneAttributes_railRoadTrackPresent	= 8,
	DSRC_CrosswalkLaneAttributes_oneWayPathOfTravel	= 16,
	DSRC_CrosswalkLaneAttributes_pedestrianCrosswalkTypeA	= 32,
	DSRC_CrosswalkLaneAttributes_pedestrianCrosswalkTypeB	= 64,
	DSRC_CrosswalkLaneAttributes_pedestrianCrosswalkTypeC	= 128
} e_DSRC_CrosswalkLaneAttributes;

/* DSRC_CrosswalkLaneAttributes */
typedef long	 DSRC_CrosswalkLaneAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_CrosswalkLaneAttributes;
asn_struct_free_f DSRC_CrosswalkLaneAttributes_free;
asn_struct_print_f DSRC_CrosswalkLaneAttributes_print;
asn_constr_check_f DSRC_CrosswalkLaneAttributes_constraint;
ber_type_decoder_f DSRC_CrosswalkLaneAttributes_decode_ber;
der_type_encoder_f DSRC_CrosswalkLaneAttributes_encode_der;
xer_type_decoder_f DSRC_CrosswalkLaneAttributes_decode_xer;
xer_type_encoder_f DSRC_CrosswalkLaneAttributes_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_CrosswalkLaneAttributes_H_ */
#include <asn_internal.h>
