/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_VehicleSafetyExtension_H_
#define	_DSRC_VehicleSafetyExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_EventFlags.h"
#include "DSRC_PathHistory.h"
#include "DSRC_PathPrediction.h"
#include "DSRC_RTCMPackage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_VehicleSafetyExtension */
typedef struct DSRC_VehicleSafetyExtension {
	DSRC_EventFlags_t	*events	/* OPTIONAL */;
	DSRC_PathHistory_t	*pathHistory	/* OPTIONAL */;
	DSRC_PathPrediction_t	*pathPrediction	/* OPTIONAL */;
	DSRC_RTCMPackage_t	*theRTCM	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_VehicleSafetyExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_VehicleSafetyExtension;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_VehicleSafetyExtension_H_ */
#include <asn_internal.h>
