/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_TravelerInformation_H_
#define	_DSRC_TravelerInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_UniqueMSGID.h"
#include "DSRC_URL-Base.h"
#include "DSRC_Count.h"
#include "DSRC_MsgCRC.h"
#include <asn_SEQUENCE_OF.h>
#include "DSRC_TravelerInfoType.h"
#include "DSRC_DYear.h"
#include "DSRC_MinuteOfTheYear.h"
#include "DSRC_MinutesDuration.h"
#include "DSRC_SignPrority.h"
#include "DSRC_Position3D.h"
#include "DSRC_LaneWidth.h"
#include "DSRC_DirectionOfUse.h"
#include "DSRC_URL-Short.h"
#include "DSRC_FurtherInfoID.h"
#include "DSRC_RoadSignID.h"
#include <constr_CHOICE.h>
#include "DSRC_ValidRegion.h"
#include <constr_SEQUENCE_OF.h>
#include "DSRC_ITIScodesAndText.h"
#include "DSRC_WorkZone.h"
#include "DSRC_GenericSignage.h"
#include "DSRC_SpeedLimit.h"
#include "DSRC_ExitService.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum msgId_PR {
	msgId_PR_NOTHING,	/* No components present */
	msgId_PR_furtherInfoID,
	msgId_PR_roadSignID
} msgId_PR;
typedef enum content_PR {
	content_PR_NOTHING,	/* No components present */
	content_PR_advisory,
	content_PR_workZone,
	content_PR_genericSign,
	content_PR_speedLimit,
	content_PR_exitService
} content_PR;

/* DSRC_TravelerInformation */
typedef struct DSRC_TravelerInformation {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_UniqueMSGID_t	*packetID	/* OPTIONAL */;
	DSRC_URL_Base_t	*urlB	/* OPTIONAL */;
	DSRC_Count_t	*dataFrameCount	/* OPTIONAL */;
	struct DSRC_TravelerInformation__dataFrames {
		A_SEQUENCE_OF(struct DSRC_TravelerInformation__dataFrames__Member {
			DSRC_TravelerInfoType_t	 frameType;
			struct msgId {
				msgId_PR present;
				union msgId_u {
					DSRC_FurtherInfoID_t	 furtherInfoID;
					DSRC_RoadSignID_t	 roadSignID;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} msgId;
			DSRC_DYear_t	*startYear	/* OPTIONAL */;
			DSRC_MinuteOfTheYear_t	 startTime;
			DSRC_MinutesDuration_t	 duratonTime;
			DSRC_SignPrority_t	 priority;
			DSRC_Position3D_t	*commonAnchor	/* OPTIONAL */;
			DSRC_LaneWidth_t	*commonLaneWidth	/* OPTIONAL */;
			DSRC_DirectionOfUse_t	*commonDirectionality	/* OPTIONAL */;
			struct regions {
				A_SEQUENCE_OF(DSRC_ValidRegion_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} regions;
			struct content {
				content_PR present;
				union content_u {
					DSRC_ITIScodesAndText_t	 advisory;
					DSRC_WorkZone_t	 workZone;
					DSRC_GenericSignage_t	 genericSign;
					DSRC_SpeedLimit_t	 speedLimit;
					DSRC_ExitService_t	 exitService;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} content;
			DSRC_URL_Short_t	*url	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dataFrames;
	DSRC_MsgCRC_t	 crc;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_TravelerInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_TravelerInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_TravelerInformation_H_ */
#include <asn_internal.h>
