/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_VehicleType_H_
#define	_DSRC_VehicleType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_VehicleType {
	DSRC_VehicleType_none	= 0,
	DSRC_VehicleType_unknown	= 1,
	DSRC_VehicleType_special	= 2,
	DSRC_VehicleType_moto	= 3,
	DSRC_VehicleType_car	= 4,
	DSRC_VehicleType_carOther	= 5,
	DSRC_VehicleType_bus	= 6,
	DSRC_VehicleType_axleCnt2	= 7,
	DSRC_VehicleType_axleCnt3	= 8,
	DSRC_VehicleType_axleCnt4	= 9,
	DSRC_VehicleType_axleCnt4Trailer	= 10,
	DSRC_VehicleType_axleCnt5Trailer	= 11,
	DSRC_VehicleType_axleCnt6Trailer	= 12,
	DSRC_VehicleType_axleCnt5MultiTrailer	= 13,
	DSRC_VehicleType_axleCnt6MultiTrailer	= 14,
	DSRC_VehicleType_axleCnt7MultiTrailer	= 15
	/*
	 * Enumeration is extensible
	 */
} e_DSRC_VehicleType;

/* DSRC_VehicleType */
typedef long	 DSRC_VehicleType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_VehicleType;
asn_struct_free_f DSRC_VehicleType_free;
asn_struct_print_f DSRC_VehicleType_print;
asn_constr_check_f DSRC_VehicleType_constraint;
ber_type_decoder_f DSRC_VehicleType_decode_ber;
der_type_encoder_f DSRC_VehicleType_encode_der;
xer_type_decoder_f DSRC_VehicleType_decode_xer;
xer_type_encoder_f DSRC_VehicleType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_VehicleType_H_ */
#include <asn_internal.h>
