/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_DSRC_ProbeVehicleData_H_
#define	_DSRC_ProbeVehicleData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRC_DSRCmsgID.h"
#include "DSRC_ProbeSegmentNumber.h"
#include "DSRC_VehicleIdent.h"
#include "DSRC_FullPositionVector.h"
#include "DSRC_VehicleType.h"
#include "DSRC_Count.h"
#include "DSRC_Snapshot.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSRC_ProbeVehicleData */
typedef struct DSRC_ProbeVehicleData {
	DSRC_DSRCmsgID_t	 msgID;
	DSRC_ProbeSegmentNumber_t	*segNum	/* OPTIONAL */;
	DSRC_VehicleIdent_t	*probeID	/* OPTIONAL */;
	DSRC_FullPositionVector_t	 startVector;
	DSRC_VehicleType_t	 vehicleType;
	DSRC_Count_t	*cntSnapshots	/* OPTIONAL */;
	struct DSRC_ProbeVehicleData__snapshots {
		A_SEQUENCE_OF(DSRC_Snapshot_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} snapshots;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSRC_ProbeVehicleData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRC_ProbeVehicleData;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_ProbeVehicleData_H_ */
#include <asn_internal.h>
